import { supabase } from './supabaseClient.js'

const API='https://oycwqpqoxgohzqivclzd.supabase.co'
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpYj'
const AUTH='vanidaxi-auth-session'
const readSession=()=>{try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch{return null}}
const token=()=>readSession()?.access_token||''
const uid=()=>readSession()?.user?.id||''
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const rest=async(path,options={})=>{const r=await fetch(`${API}/rest/v1/${path}`,{...options,headers:{apikey:KEY,Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error(await r.text().catch(()=>`Supabase ${r.status}`));return r.status===204?null:r.json().catch(()=>null)}

let overlay=null
const close=()=>{overlay?.remove();overlay=null}
const shell=(title,body)=>{close();overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:rgba(15,23,42,.42);backdrop-filter:blur(4px);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;font-family:inherit';overlay.innerHTML=`<div style="width:min(560px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 24px 70px rgba(0,0,0,.2)"><div style="display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px"><div><small style="letter-spacing:.12em;color:#64748b">MI CUENTA</small><h2 style="margin:5px 0 0;font-size:25px">${title}</h2></div><button data-close style="border:0;background:#f1f5f9;border-radius:12px;width:40px;height:40px;font-size:22px;cursor:pointer">×</button></div>${body}</div>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-close]'))close()});return overlay}
const field=(label,id,value,type='text',extra='')=>`<label style="display:block;margin:13px 0"><span style="display:block;font-size:13px;font-weight:700;margin-bottom:6px;color:#334155">${label}</span><input id="${id}" type="${type}" value="${esc(value)}" ${extra} style="box-sizing:border-box;width:100%;padding:12px 13px;border:1px solid #cbd5e1;border-radius:12px;font:inherit;outline:none"></label>`
const primary='style="width:100%;border:0;border-radius:13px;padding:13px 16px;background:#111827;color:white;font-weight:700;cursor:pointer"'
const secondary='style="width:100%;border:1px solid #cbd5e1;border-radius:13px;padding:13px 16px;background:white;color:#111827;font-weight:700;cursor:pointer"'

async function address(){
 const s=readSession();if(!s?.user){shell('Inicia sesión','<p style="color:#64748b">Necesitas iniciar sesión para administrar tu dirección.</p>');return}
 let a=null;try{const rows=await rest(`addresses?select=*&user_id=eq.${encodeURIComponent(uid())}&order=is_default.desc,created_at.desc&limit=1`);a=rows?.[0]||null}catch(e){console.warn('[VaniDaxi account]',e)}
 const o=s.user?.user_metadata||{}
 const el=shell('Dirección de entrega',`<p style="margin-top:0;color:#64748b">Esta dirección se utilizará como destino durante el checkout.</p><form id="vd-address">${field('Nombre completo','vd-name',a?.full_name||o.name||'')}${field('Teléfono','vd-phone',a?.phone||'','tel')}${field('Calle y número','vd-street',a?.address_line1||'')}${field('Interior / referencia (opcional)','vd-line2',a?.address_line2||'')}${field('Ciudad','vd-city',a?.city||'')}${field('Estado','vd-state',a?.state||'')}${field('Código postal','vd-zip',a?.postal_code||'')}${field('País','vd-country',a?.country||'México')}<button ${primary}>Guardar dirección</button><p id="vd-address-msg" style="min-height:20px;margin:10px 0 0;color:#64748b;font-size:13px"></p></form>`)
 el.querySelector('#vd-address').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget;const msg=el.querySelector('#vd-address-msg');const data={user_id:uid(),full_name:b.querySelector('#vd-name').value.trim(),phone:b.querySelector('#vd-phone').value.trim()||null,address_line1:b.querySelector('#vd-street').value.trim(),address_line2:b.querySelector('#vd-line2').value.trim()||null,city:b.querySelector('#vd-city').value.trim(),state:b.querySelector('#vd-state').value.trim(),postal_code:b.querySelector('#vd-zip').value.trim(),country:b.querySelector('#vd-country').value.trim()||'México',is_default:true};if(!data.address_line1||!data.city||!data.postal_code){msg.textContent='Completa calle, ciudad y código postal.';return}msg.textContent='Guardando…';try{const current=await rest(`addresses?select=id&user_id=eq.${encodeURIComponent(uid())}&is_default=eq.true&limit=1`);if(current?.[0]?.id)await rest(`addresses?id=eq.${encodeURIComponent(current[0].id)}&user_id=eq.${encodeURIComponent(uid())}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});else await rest('addresses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});localStorage.setItem('vanidaxi-address',JSON.stringify({name:data.full_name,phone:data.phone,street:data.address_line1,line2:data.address_line2,city:data.city,state:data.state,zip:data.postal_code,country:data.country}));msg.textContent='Dirección guardada correctamente.';setTimeout(close,650)}catch(err){msg.textContent='No se pudo guardar la dirección. Intenta nuevamente.';console.error(err)}})
}

function security(){
 const s=readSession();if(!s?.user){shell('Seguridad y cuenta','<p style="color:#64748b">Necesitas iniciar sesión para administrar la seguridad.</p>');return}
 const el=shell('Seguridad y cuenta',`<p style="color:#64748b;margin-top:0">Actualiza tu contraseña o cierra la sesión actual.</p><form id="vd-password">${field('Nueva contraseña','vd-password-new','','password','minlength="8"')}${field('Repite la contraseña','vd-password-repeat','','password','minlength="8"')}<button ${primary}>Actualizar contraseña</button><p id="vd-password-msg" style="min-height:20px;margin:10px 0 18px;color:#64748b;font-size:13px"></p></form><button id="vd-signout" ${secondary}>Cerrar sesión</button>`)
 el.querySelector('#vd-password').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget,n=b.querySelector('#vd-password-new').value,r=b.querySelector('#vd-password-repeat').value,msg=el.querySelector('#vd-password-msg');if(n.length<8){msg.textContent='La contraseña debe tener al menos 8 caracteres.';return}if(n!==r){msg.textContent='Las contraseñas no coinciden.';return}msg.textContent='Actualizando…';const {error}=await supabase.auth.updateUser({password:n});if(error){msg.textContent=error.message||'No se pudo actualizar la contraseña.';return}msg.textContent='Contraseña actualizada correctamente.';b.reset()})
 el.querySelector('#vd-signout').addEventListener('click',async()=>{const {error}=await supabase.auth.signOut({scope:'local'});if(error){console.error(error);return}['vanidaxi-auth-session','vanidaxi-address','vanidaxi-favorites','vanidaxi-cart','vanidaxi-payment-method'].forEach(k=>localStorage.removeItem(k));close();location.hash='#/home';location.reload()})
}

function bind(){document.querySelectorAll('.profile-links button').forEach((b,i)=>{if(b.dataset.vdBound)return;b.dataset.vdBound='1';b.addEventListener('click',e=>{e.preventDefault();i===0?address():security()})})}
const observer=new MutationObserver(bind)
observer.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind()
