import React,{useEffect,useState}from'react'
import{Check,RefreshCw,XCircle,ArrowLeft,Star}from'lucide-react'
import{moderateReview}from'./adminReviewApi.js'
import'./admin-dashboard.css'

const URL='https://oycwqpqoxgohzqivclzd.supabase.co'
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpY'
const session=()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-auth-session')||'null')}catch{return null}}
const date=v=>v?new Date(v).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'}):'—'
async function api(path,token,options={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...options,headers:{apikey:KEY,Authorization:`Bearer ${token||KEY}`,...(options.headers||{})}});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.message||d?.hint||'Error de Supabase');return d}
export default function AdminReviewModeration({back}){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const s=session();const uid=s?.user?.id;if(!uid)throw Error('Sesión requerida');const token=s.access_token||KEY;const p=await api(`profiles?select=id,role,is_active&id=eq.${encodeURIComponent(uid)}&limit=1`,token);if(p?.[0]?.role!=='admin'||!p?.[0]?.is_active)throw Error('Acceso administrativo no autorizado');const reviews=await api('reviews?select=id,product_id,user_id,order_id,rating,title,comment,is_approved,created_at,updated_at&order=is_approved.asc,created_at.desc&limit=300',token)||[];const productIds=[...new Set(reviews.map(x=>x.product_id).filter(Boolean))],userIds=[...new Set(reviews.map(x=>x.user_id).filter(Boolean))];const[products,users]=await Promise.all([productIds.length?api(`products?select=id,name&id=in.(${productIds.join(',')})`,token):Promise.resolve([]),userIds.length?api(`profiles?select=id,full_name,username&id=in.(${userIds.join(',')})`,token):Promise.resolve([])]);const pm=new Map((products||[]).map(x=>[x.id,x.name])),um=new Map((users||[]).map(x=>[x.id,x.full_name||x.username||'Usuario']));setRows(reviews.map(r=>({...r,product_name:pm.get(r.product_id)||'Producto',user_name:um.get(r.user_id)||'Usuario'})))}catch(e){setError(e.message||'No se pudieron cargar las reseñas')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const act=async(r,status)=>{setBusy(r.id);setError('');setNotice('');try{await moderateReview(r.id,status);setNotice(status==='approved'?'Reseña aprobada.':'Reseña retirada/rechazada.');await load()}catch(e){setError(e.message||'No se pudo moderar la reseña')}finally{setBusy('')}}
 const pending=rows.filter(r=>!r.is_approved),approved=rows.filter(r=>r.is_approved)
 if(loading)return <div className="admin-screen"><div className="admin-loading"><RefreshCw className="spin"/>Cargando moderación de reseñas…</div></div>
 return <div className="admin-screen"><header className="admin-top"><div><span>VaniDaxi · REPUTACIÓN</span><h1>Moderación de reseñas</h1><p>Revisa las opiniones de compras verificadas antes de publicarlas.</p></div><div className="admin-top-actions"><button className="admin-refresh" onClick={load}><RefreshCw size={16}/>Actualizar</button><button className="admin-refresh" onClick={back}><ArrowLeft size={16}/>Volver al panel</button></div></header>{error&&<div className="admin-error">{error}</div>}{notice&&<div className="admin-notice">{notice}</div>}<section className="admin-kpis"><Kpi label="Pendientes" value={pending.length}/><Kpi label="Publicadas" value={approved.length}/><Kpi label="Total" value={rows.length}/></section><ReviewList title="Pendientes de aprobación" rows={pending} busy={busy} act={act} pending/><ReviewList title="Reseñas publicadas" rows={approved} busy={busy} act={act}/></div>
}
const Kpi=({label,value})=><div className="admin-kpi"><span><Star size={18}/></span><small>{label}</small><strong>{value}</strong></div>
function ReviewList({title,rows,busy,act,pending=false}){return <section className="admin-card admin-panel"><h2 className="admin-section-title">{title}</h2>{rows.length?<div className="admin-list">{rows.map(r=><article className="admin-review-row" key={r.id}><div><b>{r.product_name}</b><small>{r.user_name} · {date(r.created_at)} · Pedido {r.order_id||'—'}</small><div className="admin-review-rating">{'★'.repeat(Math.max(0,Math.min(5,Number(r.rating||0))))}{'☆'.repeat(5-Math.max(0,Math.min(5,Number(r.rating||0))))}</div>{r.title&&<strong>{r.title}</strong>}{r.comment&&<p>{r.comment}</p>}</div><aside>{pending?<><button onClick={()=>act(r,'approved')} disabled={busy===r.id}><Check size={14}/>Aprobar</button><button onClick={()=>act(r,'rejected')} disabled={busy===r.id}><XCircle size={14}/>Rechazar</button></>:<button onClick={()=>act(r,'rejected')} disabled={busy===r.id}><XCircle size={14}/>Retirar</button>}</aside></article>)}</div>:<div className="admin-empty">No hay reseñas en esta sección.</div>}</section>}
