/* VaniDaxi — registro e inicio de sesión */
(() => {
  const SUPABASE_URL = 'https://oycwqpqoxgohzqivclzd.supabase.co'
  const SUPABASE_KEY = 'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpYj'
  const SESSION_KEY = 'vanidaxi-auth-session'
  const getSession = () => { try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null') } catch { return null } }
  const saveSession = s => localStorage.setItem(SESSION_KEY, JSON.stringify({access_token:s.access_token,refresh_token:s.refresh_token,user:s.user}))
  const api = async (path, body) => { const r = await fetch(`${SUPABASE_URL}${path}`, {method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.msg||d.message||d.error_description||'No se pudo completar la operación'); return d }
  const css=document.createElement('style');css.textContent=`.vd-account{position:fixed;right:16px;bottom:78px;z-index:9998;border:0;border-radius:999px;padding:11px 15px;background:linear-gradient(135deg,#70429a,#c45aa5);color:#fff;font:800 13px Inter,system-ui,sans-serif;box-shadow:0 8px 24px #70429a44;cursor:pointer}.vd-auth{position:fixed;inset:0;z-index:100001;display:grid;place-items:center;padding:20px;background:#21152b99;backdrop-filter:blur(8px);font-family:Inter,system-ui,sans-serif}.vd-auth-card{width:min(430px,100%);background:#fff;border-radius:28px;padding:26px;box-shadow:0 25px 80px #26153255}.vd-auth-brand{font-size:22px;font-weight:900;color:#70429a}.vd-auth-card h2{margin:18px 0 7px;font-size:25px;color:#29222f}.vd-auth-card p{color:#756a7c;font-size:14px;line-height:1.45;margin:0 0 18px}.vd-auth-card label{display:block;font-size:12px;font-weight:800;color:#514656;margin:12px 0 6px}.vd-auth-card input{width:100%;padding:13px 14px;border:1px solid #e4dce8;border-radius:14px;outline:none;font:inherit}.vd-auth-card input:focus{border-color:#9b62b8}.vd-auth-main{width:100%;margin-top:18px;border:0;border-radius:15px;padding:14px;background:linear-gradient(135deg,#70429a,#c45aa5);color:#fff;font-weight:900;cursor:pointer}.vd-auth-link,.vd-auth-close{border:0;background:transparent;cursor:pointer;color:#70429a;font-weight:800}.vd-auth-link{display:block;width:100%;padding:12px;margin-top:5px}.vd-auth-msg{min-height:18px;margin-top:10px;font-size:12px;color:#70429a}.vd-auth-user{display:flex;align-items:center;gap:10px}.vd-auth-user strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.vd-auth-logout{margin-left:auto;border:0;background:#f3eafa;color:#70429a;border-radius:10px;padding:8px 10px;font-weight:800}`;document.head.appendChild(css)
  const open = () => { if(document.querySelector('.vd-auth')) return; const session=getSession(); const e=document.createElement('div');e.className='vd-auth';e.innerHTML=`<div class="vd-auth-card"><div class="vd-auth-brand">✦ VaniDaxi</div><div class="vd-auth-body"></div></div>`;document.body.appendChild(e);e.onclick=x=>{if(x.target===e)e.remove()};render(e.querySelector('.vd-auth-body'),session)}
  const render=(body,session)=>{if(session?.user){body.innerHTML=`<h2>Mi cuenta</h2><div class="vd-auth-user"><strong>${session.user.email||'Cuenta VaniDaxi'}</strong><button class="vd-auth-logout">Cerrar sesión</button></div><p>Tu cuenta está activa. Tus datos podrán asociarse a tu experiencia de VaniDaxi.</p><button class="vd-auth-link">Cerrar</button>`;body.querySelector('.vd-auth-logout').onclick=async()=>{try{await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`}})}catch(_){}localStorage.removeItem(SESSION_KEY);body.closest('.vd-auth').remove();open()};body.querySelector('.vd-auth-link').onclick=()=>body.closest('.vd-auth').remove();return}
    let mode='signup'; body.innerHTML=`<h2>Únete a VaniDaxi 🤗</h2><p>Regístrate para guardar tu cuenta, favoritos, carrito y pedidos.</p><label>Nombre</label><input data-name autocomplete="name" placeholder="Tu nombre"><label>Correo electrónico</label><input data-email type="email" autocomplete="email" placeholder="tu@correo.com"><label>Contraseña</label><input data-pass type="password" autocomplete="new-password" placeholder="Mínimo 6 caracteres"><button class="vd-auth-main" data-main>Crear mi cuenta</button><div class="vd-auth-msg" data-msg></div><button class="vd-auth-link" data-switch>Ya tengo una cuenta</button><button class="vd-auth-link" data-close>Continuar sin cuenta</button>`
    const main=body.querySelector('[data-main]'), sw=body.querySelector('[data-switch]'), msg=body.querySelector('[data-msg]');
    sw.onclick=()=>{mode=mode==='signup'?'signin':'signup';body.querySelector('[data-name]').style.display=mode==='signup'?'block':'none';body.querySelector('[data-name]').previousElementSibling.style.display=mode==='signup'?'block':'none';main.textContent=mode==='signup'?'Crear mi cuenta':'Iniciar sesión';sw.textContent=mode==='signup'?'Ya tengo una cuenta':'Crear una cuenta';body.querySelector('[data-pass]').autocomplete=mode==='signup'?'new-password':'current-password';msg.textContent=''}
    body.querySelector('[data-close]').onclick=()=>body.closest('.vd-auth').remove()
    main.onclick=async()=>{msg.textContent='Procesando…';main.disabled=true;try{const email=body.querySelector('[data-email]').value.trim();const password=body.querySelector('[data-pass]').value;if(!email||password.length<6)throw new Error('Escribe un correo válido y una contraseña de al menos 6 caracteres.');let d;if(mode==='signup'){const name=body.querySelector('[data-name]').value.trim();d=await api('/auth/v1/signup',{email,password,data:{name}});if(d.access_token){saveSession(d);msg.textContent='Cuenta creada correctamente.';setTimeout(()=>body.closest('.vd-auth').remove(),900)}else msg.textContent='Cuenta creada. Revisa tu correo para confirmar la cuenta y después inicia sesión.'}else{d=await api('/auth/v1/token?grant_type=password',{email,password});saveSession(d);msg.textContent='Sesión iniciada.';setTimeout(()=>body.closest('.vd-auth').remove(),700)}}catch(err){msg.textContent=err.message}finally{main.disabled=false}}
  }
  window.addEventListener('load',()=>{const b=document.createElement('button');b.className='vd-account';b.textContent=getSession()?'Mi cuenta':'Registrarme / Iniciar sesión';b.onclick=open;document.body.appendChild(b)})
})()
