import React,{useRef,useState}from'react'
import{Eye,EyeOff,UserPlus,Store,LogIn,X,Check,Chrome,Facebook,Fingerprint,Phone}from'lucide-react'
import HCaptcha from '@hcaptcha/react-hcaptcha'
import{signIn,signUp,signInWithProvider,saveSession}from'./auth.js'
import{supabase}from'./supabaseClient.js'
import'./auth-choice.css'

const HCAPTCHA_SITEKEY=import.meta.env.VITE_HCAPTCHA_SITEKEY||'390a44ec-b452-47d4-8514-5e6aeeece0ee'
const passkeySupported=()=>typeof window!=='undefined'&&window.isSecureContext&&'PublicKeyCredential'in window
const normalizePhone=v=>{const raw=String(v||'').trim();if(raw.startsWith('+'))return`+${raw.slice(1).replace(/\D/g,'')}`;const digits=raw.replace(/\D/g,'');return digits.length===10?`+52${digits}`:`+${digits}`}
const validPhone=v=>/^\+\d{10,15}$/.test(normalizePhone(v))

export default function AuthChoice({type='login',close,done}){
 const initialSignup=type==='signup'||type==='seller-signup'
 const[mode,setMode]=useState(initialSignup?'signup':'login'),[accountType,setAccountType]=useState(type==='seller-signup'?'seller':'customer'),[method,setMethod]=useState('email'),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[otpSent,setOtpSent]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[passkeyBusy,setPasskeyBusy]=useState(false),[socialBusy,setSocialBusy]=useState(''),[err,setErr]=useState(''),[message,setMessage]=useState(''),[captchaToken,setCaptchaToken]=useState('');const captchaRef=useRef(null)
 const resetCaptcha=()=>{setCaptchaToken('');captchaRef.current?.resetCaptcha?.()}
 const social=async provider=>{setErr('');setMessage('');setSocialBusy(provider);try{await signInWithProvider(provider)}catch(e){setErr(e?.message||`No se pudo iniciar sesión con ${provider}.`)}finally{setSocialBusy('')}}
 const passkeyLogin=async()=>{setErr('');setMessage('');if(!passkeySupported()){setErr('Este dispositivo o navegador no tiene disponible el acceso con llave de acceso. Puedes iniciar sesión con correo y contraseña.');return}setPasskeyBusy(true);try{const{data,error}=await supabase.auth.signInWithPasskey();if(error)throw error;if(!data?.session)throw new Error('Supabase no devolvió una sesión válida.');saveSession(data.session);done(data)}catch(e){const code=e?.code||'';if(code==='passkey_disabled')setErr('El acceso con huella/Face ID todavía no está habilitado en VaniDaxi.');else if(e?.name==='NotAllowedError')setErr('La verificación con el dispositivo fue cancelada.');else setErr(e?.message||'No se pudo iniciar sesión con la llave de acceso.')}finally{setPasskeyBusy(false)}}
 const phoneOtp=async()=>{setBusy(true);setErr('');setMessage('');try{const normalized=normalizePhone(phone);if(!validPhone(phone))throw new Error('Escribe un número válido con 10 a 15 dígitos.');if(!captchaToken)throw new Error('Completa la verificación de seguridad antes de continuar.');const{error}=await supabase.auth.signInWithOtp({phone:normalized,options:{channel:'sms',captchaToken}});if(error)throw error;setOtpSent(true);setOtp('');resetCaptcha();setMessage(`Enviamos un código de 6 dígitos a ${normalized}.`)}catch(e){resetCaptcha();setErr(e?.message||'No se pudo enviar el código por SMS.')}finally{setBusy(false)}}
 const verifyPhone=async()=>{setBusy(true);setErr('');setMessage('');try{const normalized=normalizePhone(phone);if(!/^\d{6}$/.test(otp.trim()))throw new Error('Escribe el código de 6 dígitos.');const{data,error}=await supabase.auth.verifyOtp({phone:normalized,token:otp.trim(),type:'sms'});if(error)throw error;if(!data?.session)throw new Error('Supabase no devolvió una sesión válida.');saveSession(data.session);done(data)}catch(e){setErr(e?.message||'No se pudo verificar el código.')}finally{setBusy(false)}}
 const submit=async e=>{e.preventDefault();if(method==='phone'){if(otpSent)await verifyPhone();else await phoneOtp();return}setBusy(true);setErr('');setMessage('');try{if(!captchaToken)throw new Error('Completa la verificación de seguridad antes de continuar.');if(mode==='signup'){if(!name.trim())throw new Error('Escribe tu nombre.');const r=await signUp(email.trim(),pw,name.trim(),accountType,captchaToken);resetCaptcha();if(r?.access_token)done(r);else{setMessage(accountType==='seller'?'Cuenta de vendedor creada. Confirma tu correo si se solicita y después inicia sesión.':'Cuenta de comprador creada. Confirma tu correo si se solicita y después inicia sesión.');setMode('login')}}else{const r=await signIn(email.trim(),pw,captchaToken);resetCaptcha();done(r)}}catch(e){resetCaptcha();setErr(e?.message||'No se pudo completar la operación.')}finally{setBusy(false)}}
 const switchMode=()=>{setMode(v=>v==='signup'?'login':'signup');setErr('');setMessage('');setMethod('email');setOtpSent(false);setOtp('');resetCaptcha()}
 return <div className="vd-auth-backdrop" role="dialog" aria-modal="true"><div className="vd-auth-card"><button className="vd-auth-close" onClick={close} aria-label="Cerrar"><X size={18}/></button><div className="vd-auth-brand"><span>V</span><b>VaniDaxi</b></div><div className="vd-auth-head"><h2>{mode==='signup'?'Crear cuenta':'Bienvenido de nuevo'}</h2><p>{mode==='signup'?'Elige cómo quieres usar VaniDaxi.':'Inicia sesión para continuar.'}</p></div>
 {mode==='login'&&<><button type="button" onClick={passkeyLogin} disabled={passkeyBusy||!!socialBusy} style={{width:'100%',display:'flex',alignItems:'center',justifyContent:'center',gap:9,border:'1px solid #d8b4fe',borderRadius:13,padding:'12px 14px',background:'#faf5ff',color:'#5b21b6',fontWeight:800,cursor:'pointer',marginBottom:12}}><Fingerprint size={19}/>{passkeyBusy?'Verificando…':'Entrar con huella, Face ID o PIN'}</button><div className="vd-divider"><span>o continúa con otra opción</span></div></>}
 {method==='email'&&mode==='login'&&<div className="vd-social-grid"><button type="button" onClick={()=>social('google')} disabled={!!socialBusy||passkeyBusy}><Chrome size={18}/><span>{socialBusy==='google'?'Conectando…':'Continuar con Google'}</span></button><button type="button" onClick={()=>social('facebook')} disabled={!!socialBusy||passkeyBusy}><Facebook size={18}/><span>{socialBusy==='facebook'?'Conectando…':'Continuar con Facebook'}</span></button></div>}
 {method==='email'&&<div className="vd-divider"><span>{mode==='login'?'o continúa con otra opción':'elige cómo registrarte'}</span></div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9,marginBottom:14}}><button type="button" onClick={()=>{setMethod('email');setOtpSent(false);setErr('');setMessage('');resetCaptcha()}} disabled={method==='email'} style={{minHeight:44,border:'1px solid #e6ddea',borderRadius:13,background:method==='email'?'#faf5fd':'#fff',color:'#44374d',fontWeight:750,cursor:method==='email'?'default':'pointer'}}>✉️ Correo</button><button type="button" onClick={()=>{setMethod('phone');setAccountType('customer');setOtpSent(false);setOtp('');setErr('');setMessage('');resetCaptcha()}} disabled={method==='phone'} style={{minHeight:44,border:'1px solid #e6ddea',borderRadius:13,background:method==='phone'?'#faf5fd':'#fff',color:'#44374d',fontWeight:750,cursor:method==='phone'?'default':'pointer',display:'flex',alignItems:'center',justifyContent:'center',gap:7}}><Phone size={17}/>Teléfono</button></div>
 {mode==='signup'&&method==='email'&&<div className="vd-role-grid"><button type="button" className={`vd-role ${accountType==='customer'?'active':''}`} onClick={()=>setAccountType('customer')}><UserPlus size={20}/><span><b>Comprador</b><small>Comprar y gestionar mis pedidos</small></span>{accountType==='customer'&&<Check size={16}/>}</button><button type="button" className={`vd-role ${accountType==='seller'?'active':''}`} onClick={()=>setAccountType('seller')}><Store size={20}/><span><b>Vendedor</b><small>Publicar productos y administrar mi tienda</small></span>{accountType==='seller'&&<Check size={16}/>}</button></div>}
 <form onSubmit={submit} className="vd-auth-form">{method==='phone'?<>{!otpSent?<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Número de teléfono · Ej. 669 123 4567" inputMode="tel" autoComplete="tel" required/>:<><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Código SMS de 6 dígitos" inputMode="numeric" autoComplete="one-time-code" required/><button type="button" className="vd-auth-switch" style={{padding:'3px 0 0',textAlign:'left'}} onClick={()=>{setOtpSent(false);setOtp('');setMessage('');setErr('');}}>Cambiar número</button></>}<div className="vd-captcha"><HCaptcha ref={captchaRef} sitekey={HCAPTCHA_SITEKEY} onVerify={token=>setCaptchaToken(token)} onExpire={()=>setCaptchaToken('')} onError={()=>setCaptchaToken('')}/></div><button className="vd-auth-submit" disabled={busy}>{busy?(otpSent?'Verificando…':'Enviando código…'):(otpSent?'Verificar código':'Enviar código SMS')} <Phone size={16}/></button></>:<><>{mode==='signup'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre completo" autoComplete="name" required/>}</><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Correo electrónico" type="email" autoComplete="email" required/><div className="vd-pass"><input value={pw} onChange={e=>setPw(e.target.value)} placeholder="Contraseña" type={show?'text':'password'} minLength={6} autoComplete={mode==='signup'?'new-password':'current-password'} required/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><div className="vd-captcha"><HCaptcha ref={captchaRef} sitekey={HCAPTCHA_SITEKEY} onVerify={token=>setCaptchaToken(token)} onExpire={()=>setCaptchaToken('')} onError={()=>setCaptchaToken('')}/></div><button className="vd-auth-submit" disabled={busy}>{busy?'Procesando…':mode==='signup'?(accountType==='seller'?'Crear cuenta de vendedor':'Crear cuenta de comprador'):'Iniciar sesión'} <LogIn size={16}/></button></>}</form>
 {method==='phone'&&<div style={{marginTop:10,fontSize:12,color:'#887d91'}}>El acceso por teléfono usa un código SMS de un solo uso. Para proteger los permisos de vendedor, el alta por teléfono comienza como comprador.</div>}
 {message&&<div className="vd-auth-message">{message}</div>}{err&&<div className="vd-auth-error">{err}</div>}<button className="vd-auth-switch" onClick={switchMode}>{mode==='signup'?'Ya tengo una cuenta':'Crear una cuenta nueva'}</button></div></div>
}

// VaniDaxi auth CAPTCHA provider: hCaptcha.
