import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,Heart,Plus,Search,SlidersHorizontal,ShoppingBag,X}from'lucide-react'
import{fetchCatalog}from'./commercialApi.js'
import'./catalog-advanced.css'
const money=v=>`$${Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const image=p=>p?.image_url||(Array.isArray(p?.images)?p.images[0]:'')||''
const readCart=()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-cart')||'[]')}catch{return[]}}
export default function CatalogAdvanced({back}){
 const[data,setData]=useState({categories:[],products:[]}),[q,setQ]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('relevance'),[availability,setAvailability]=useState('all'),[offers,setOffers]=useState(false),[liked,setLiked]=useState(()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-favorites')||'[]')}catch{return[]}}),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{fetchCatalog().then(x=>setData(x||{categories:[],products:[]})).finally(()=>setLoading(false))},[])
 const products=useMemo(()=>{let a=(data.products||[]).filter(p=>p.status==='approved');if(category)a=a.filter(p=>String(p.category_id)===String(category));if(availability==='available')a=a.filter(p=>Number(p.stock)>0);if(availability==='low')a=a.filter(p=>Number(p.stock)>0&&Number(p.stock)<=5);if(offers)a=a.filter(p=>Number(p.compare_at_price)>Number(p.price));if(q){const s=q.toLowerCase().trim();a=a.filter(p=>`${p.name} ${p.description||''} ${p.sku||''}`.toLowerCase().includes(s))}if(sort==='price-low')a.sort((a,b)=>Number(a.price)-Number(b.price));if(sort==='price-high')a.sort((a,b)=>Number(b.price)-Number(a.price));if(sort==='newest')a.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return a},[data,q,category,sort,availability,offers])
 const toggle=id=>setLiked(v=>{const n=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem('vanidaxi-favorites',JSON.stringify(n));return n})
 const add=p=>{const cart=readCart(),i=cart.findIndex(x=>String(x.product?.id)===String(p.id));const next=i>=0?cart.map((x,j)=>j===i?{...x,qty:Number(x.qty||1)+1}:x):[...cart,{product:p,qty:1}];localStorage.setItem('vanidaxi-cart',JSON.stringify(next));setNotice('Producto agregado al carrito');setTimeout(()=>setNotice(''),1800)}
 return <section className="catalog-advanced"><div className="catalog-top"><button className="catalog-back" onClick={back}><ArrowLeft/>Volver</button><div><small>VaniDaxi MARKETPLACE</small><h1>Descubre productos</h1><p>Busca, filtra y encuentra lo que necesitas.</p></div></div>{notice&&<div className="catalog-notice">{notice}</div>}<div className="catalog-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Busca productos, marcas y más"/><button onClick={()=>{setQ('');setCategory('');setOffers(false);setAvailability('all')}}><X/>Limpiar</button></div><div className="catalog-layout"><aside className="catalog-filters"><div className="filter-heading"><SlidersHorizontal/><b>Filtrar</b></div><label>Categoría<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Disponibilidad<select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">Todas</option><option value="available">Disponible</option><option value="low">Últimas unidades</option></select></label><label className="check"><input type="checkbox" checked={offers} onChange={e=>setOffers(e.target.checked)}/> Solo ofertas</label></aside><div className="catalog-results"><div className="catalog-result-head"><span>{loading?'Cargando…':`${products.length} productos`}</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">Relevancia</option><option value="newest">Más recientes</option><option value="price-low">Precio: menor a mayor</option><option value="price-high">Precio: mayor a menor</option></select></div>{loading?<div className="catalog-empty">Preparando catálogo…</div>:products.length?<div className="catalog-grid">{products.map(p=><article className="catalog-card" key={p.id}><div className="catalog-img">{image(p)?<img src={image(p)} alt=""/>:<span>VaniDaxi</span>}{Number(p.compare_at_price)>Number(p.price)&&<b>Oferta</b>}<button onClick={()=>toggle(p.id)} className={liked.includes(p.id)?'liked':''}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/></button></div><div className="catalog-body"><small>{p.sku||'VaniDaxi'}</small><h3>{p.name}</h3><strong>{money(p.price)}</strong>{Number(p.compare_at_price)>Number(p.price)&&<del>{money(p.compare_at_price)}</del>}<span className={Number(p.stock)>0?'available':'soldout'}>{Number(p.stock)>0?(Number(p.stock)<=5?`Últimas ${p.stock} unidades`:'Disponible'):'Agotado'}</span><button disabled={!Number(p.stock)} onClick={()=>add(p)}><ShoppingBag/><Plus/>Agregar al carrito</button></div></article>)}</div>:<div className="catalog-empty"><b>No encontramos productos con estos filtros.</b><span>Prueba otra búsqueda o elimina algún filtro.</span></div>}</div></div></section>
}