const SUPABASE_URL='https://oycwqpqoxgohzqivclzd.supabase.co'
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpY'
const AUTH_KEY='vanidaxi-auth-session'
const headers=(token)=>({apikey:KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})})
const session=()=>{try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
const token=()=>session()?.access_token||''
const uid=()=>session()?.user?.id||''
async function rest(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{...headers(token()),...(options.headers||{})}});if(!r.ok){const e=await r.text().catch(()=> '');throw new Error(e||`Supabase ${r.status}`)}return r.status===204?null:r.json().catch(()=>null)}
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(token()),body:JSON.stringify(body||{})});if(!r.ok){const e=await r.text().catch(()=> '');throw new Error(e||`Supabase ${r.status}`)}return r.json().catch(()=>null)}
function read(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
export async function fetchCatalog(){const results=await Promise.allSettled([rest('categories?select=id,name,slug,description,image_url,is_active&is_active=eq.true&order=name'),rest('products?select=id,seller_id,category_id,name,slug,description,price,compare_at_price,stock,sku,image_url,images,status,created_at&status=eq.approved&order=created_at.desc')]);const categories=results[0].status==='fulfilled'?(results[0].value||[]):[];const products=results[1].status==='fulfilled'?(results[1].value||[]):[];return{categories,products}}
export async function loadCommercialState(){if(!uid())return null;const userId=encodeURIComponent(uid());const[favorites,addresses,cartRows,orders,profile]=await Promise.all([rest(`favorites?select=product_id&user_id=eq.${userId}`),rest(`addresses?select=*&user_id=eq.${userId}&order=is_default.desc,created_at.desc`),rest(`carts?select=id,updated_at&user_id=eq.${userId}&limit=1`),rest(`orders?select=id,order_number,status,subtotal,discount,shipping_cost,total,shipping_address,payment_provider,delivery_provider,delivery_status,delivery_tracking,delivery_notes,delivery_custody,delivery_updated_at,delivery_handoff_at,delivery_received_at,delivered_at,created_at&user_id=eq.${userId}&order=created_at.desc`),rest(`profiles?select=id,full_name,username,avatar_url,phone,role,is_active&id=eq.${userId}&limit=1`)]);let cart=[];if(cartRows?.[0]?.id)cart=await rest(`cart_items?select=product_id,quantity,cart_id&cart_id=eq.${encodeURIComponent(cartRows[0].id)}`)||[];const orderIds=(orders||[]).map(x=>x.id).filter(Boolean);let orderItems=[];if(orderIds.length)orderItems=await rest(`order_items?select=id,order_id,product_id,product_name,quantity,unit_price,total_price,seller_id&order_id=in.(${orderIds.map(encodeURIComponent).join(',')})`)||[];const grouped=new Map();for(const x of orderItems){const a=grouped.get(x.order_id)||[];a.push(x);grouped.set(x.order_id,a)}return{favorites:(favorites||[]).map(x=>x.product_id),addresses:addresses||[],cart,orders:(orders||[]).map(o=>({...o,items:grouped.get(o.id)||[]})),profile:profile?.[0]||null}}
export async function syncProfile(){if(!uid())return false;const id=encodeURIComponent(uid()),current=await rest(`profiles?select=id,full_name,username,phone&id=${id}&limit=1`),u=session()?.user||{},metadata=u.user_metadata||{},row={id:uid(),full_name:metadata.name||metadata.full_name||u.email?.split('@')[0]||'Usuario'};if(current?.[0])await rest(`profiles?id=${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});else await rest('profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});return true}
export async function syncFavorites(productIds){if(!uid())return false;const ids=(productIds||[]).filter(x=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(x))),existing=await rest(`favorites?select=id,product_id&user_id=eq.${encodeURIComponent(uid())}`)||[],want=new Set(ids.map(String)),have=new Map(existing.map(x=>[String(x.product_id),x]));await Promise.all(existing.filter(x=>!want.has(String(x.product_id))).map(x=>rest(`favorites?id=eq.${encodeURIComponent(x.id)}&user_id=eq.${encodeURIComponent(uid())}`,{method:'DELETE'})));await Promise.all(ids.filter(id=>!have.has(String(id))).map(product_id=>rest('favorites',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:uid(),product_id})})));return true}
export async function syncAddress(address){if(!uid()||!address?.street||!address?.city||!address?.zip)return false;const current=await rest(`addresses?select=id&user_id=eq.${encodeURIComponent(uid())}&is_default=eq.true&limit=1`),row={user_id:uid(),full_name:address.name||'Mi cuenta',phone:address.phone||null,address_line1:address.street,address_line2:address.line2||null,city:address.city,state:address.state||'',postal_code:address.zip,country:address.country||'México',is_default:true};if(current?.[0]?.id)await rest(`addresses?id=eq.${encodeURIComponent(current[0].id)}&user_id=eq.${encodeURIComponent(uid())}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});else await rest('addresses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});return true}
export async function syncCart(cart,catalog){if(!uid())return false;const remote=await rest(`carts?select=id&user_id=eq.${encodeURIComponent(uid())}&limit=1`);let cartId=remote?.[0]?.id;if(!cartId){const made=await rest('carts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:uid()})});cartId=made?.[0]?.id}if(!cartId)return false;await rest(`cart_items?cart_id=eq.${encodeURIComponent(cartId)}`,{method:'DELETE'});const rows=(cart||[]).map(x=>{const p=(catalog||[]).find(p=>String(p.id)===String(x.product?.id)||p.slug===x.product?.slug);return p?.id?{cart_id:cartId,product_id:p.id,quantity:Math.max(1,Number(x.qty||1))}:null}).filter(Boolean);if(rows.length)await rest('cart_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)});return true}
export async function loadCheckoutQuote(items,catalog){const mapped=(items||[]).map(x=>{const p=(catalog||[]).find(p=>String(p.id)===String(x.product?.id)||p.slug===x.product?.slug);return p?{p,qty:Math.max(1,Math.min(100,Number(x.qty||1)))}:null}).filter(Boolean);const subtotal=Math.round(mapped.reduce((n,{p,qty})=>n+Math.max(0,Number(p.price||0))*qty,0)*100)/100;if(!uid()||!mapped.length)return{subtotal,discount:0,shipping:0,total:subtotal,promotion:null};try{const now=new Date().toISOString();const promos=await rest(`promotions?select=id,name,promotion_type,discount_value,registration_promotion,usage_limit,usage_count,start_at,end_at,created_at&is_active=eq.true&automatic=eq.true&start_at=lte.${encodeURIComponent(now)}&or=(end_at.is.null,end_at.gte.${encodeURIComponent(now)})&order=created_at.desc` )||[];for(const p of promos){if(p.usage_limit!=null&&Number(p.usage_count||0)>=Number(p.usage_limit))continue;if(p.registration_promotion){const assigned=await rest(`user_promotions?select=id&user_id=eq.${encodeURIComponent(uid())}&promotion_id=eq.${encodeURIComponent(p.id)}&used=eq.false&limit=1`);if(!assigned?.length)continue}let discount=0;if(p.promotion_type==='percentage')discount=Math.round(subtotal*Math.min(100,Math.max(0,Number(p.discount_value||0)))/100*100)/100;else if(p.promotion_type==='fixed_amount')discount=Math.min(subtotal,Math.max(0,Number(p.discount_value||0)));const shipping=0;return{subtotal,discount,shipping,total:Math.max(0,Math.round((subtotal-discount+shipping)*100)/100),promotion:p}}}catch(e){console.warn('[VaniDaxi checkout quote]',e.message)}return{subtotal,discount:0,shipping:0,total:subtotal,promotion:null}}
export async function createCommercialOrder(order,catalog){if(!uid()||!order?.items?.length)return null;const mapped=(order.items||[]).map(x=>{const p=(catalog||[]).find(p=>String(p.id)===String(x.product?.id)||p.slug===x.product?.slug);return p?{p,x}:null}).filter(Boolean);if(mapped.length!==order.items.length)return null;const items=mapped.map(({x,p})=>({product_id:p.id,qty:Math.max(1,Number(x.qty||1))}));return await rpc('create_commercial_order',{p_items:items,p_shipping_address:order.address||null})}
export async function updateOrderDelivery(orderId,status,tracking=null,notes=null){if(!uid()||!orderId)return null;return await rpc('update_order_delivery',{p_order_id:orderId,p_status:status,p_tracking:tracking,p_notes:notes})}
export async function loadOrderDeliveryEvents(orderId){if(!uid()||!orderId)return [];return await rest(`order_delivery_events?select=id,order_id,status,custody,actor_id,notes,tracking,created_at&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.asc`)||[]}
export async function createReturnRequest(payload){if(!uid()||!payload?.order_item_id||!payload?.reason)return null;return await rpc('create_return_request',{p_order_item_id:payload.order_item_id,p_reason:payload.reason,p_details:payload.details||null})}
export async function loadMyReturns(){if(!uid())return [];return await rest(`returns?select=id,order_id,order_item_id,seller_id,reason,details,status,refund_amount,resolution_notes,requested_at,resolved_at,created_at,updated_at&user_id=eq.${encodeURIComponent(uid())}&order=created_at.desc`)||[]}
export async function resolveReturn(payload){if(!uid()||!payload?.id||!payload?.status)return null;return await rpc('resolve_return',{p_return_id:payload.id,p_status:payload.status,p_notes:payload.notes||null,p_refund_amount:payload.refund_amount==null?null:Number(payload.refund_amount)})}
export async function loadSellerReturns(){if(!uid())return [];return await rpc('load_seller_returns')||[]}
export async function loadProductReviews(productId){if(!productId)return [];return await rest(`reviews?select=id,product_id,user_id,order_id,rating,title,comment,created_at&product_id=eq.${encodeURIComponent(productId)}&is_approved=eq.true&order=created_at.desc`)||[]}
export async function createReview(review){if(!uid()||!review?.product_id||!review?.rating||!review?.order_id)return null;const rows=await rest('reviews',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({product_id:review.product_id,user_id:uid(),order_id:review.order_id,rating:Math.min(5,Math.max(1,Number(review.rating))),title:review.title||null,comment:review.comment||null})});return rows?.[0]||null}
export async function loadNotifications(){if(!uid())return [];return await rest(`notifications?select=id,title,message,type,is_read,created_at&user_id=eq.${encodeURIComponent(uid())}&order=created_at.desc&limit=50`)||[]}
export async function markNotificationRead(id){if(!uid()||!id)return false;await rest(`notifications?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(uid())}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_read:true})});return true}
export async function markAllNotificationsRead(){if(!uid())return false;await rest(`notifications?user_id=eq.${encodeURIComponent(uid())}&is_read=eq.false`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_read:true})});return true}
export async function loadPromotions(){return await rest('promotions?select=id,name,description,registration_message,promotion_type,discount_value,promo_code,automatic,registration_promotion,start_at,end_at,usage_limit,usage_count,is_active&is_active=eq.true&registration_promotion=eq.true&order=created_at.desc')||[]}
export async function getMySellerStore(){if(!uid())return null;return await rpc('get_my_seller_store')}
export async function saveMySellerStore(store){if(!uid())return null;return await rpc('upsert_my_seller_store',{p_store_name:store.store_name,p_description:store.description||null,p_logo_url:store.logo_url||null,p_banner_url:store.banner_url||null})}
export async function createSellerProduct(p){if(!uid())return null;return await rpc('create_seller_product',{p_category_id:p.category_id||null,p_name:p.name,p_description:p.description||null,p_price:Number(p.price),p_compare_at_price:p.compare_at_price===''?null:Number(p.compare_at_price),p_cost_price:p.cost_price===''?null:Number(p.cost_price),p_stock:Math.max(0,Number(p.stock||0)),p_sku:p.sku||null,p_image_url:p.image_url||null,p_images:Array.isArray(p.images)?p.images:[]})}
export async function updateSellerProduct(p){if(!uid())return null;return await rpc('update_seller_product',{p_product_id:p.id,p_category_id:p.category_id||null,p_name:p.name,p_description:p.description||null,p_price:Number(p.price),p_compare_at_price:p.compare_at_price===''?null:Number(p.compare_at_price),p_cost_price:p.cost_price===''?null:Number(p.cost_price),p_stock:p.stock==null?null:Math.max(0,Number(p.stock)),p_sku:p.sku||null,p_image_url:p.image_url||null,p_images:Array.isArray(p.images)?p.images:null})}
export async function deleteSellerProduct(id){if(!uid()||!id)return false;return await rpc('delete_seller_product',{p_product_id:id})}
export async function restockSellerProduct(id,quantity,note=''){if(!uid()||!id)return null;return await rpc('restock_seller_product',{p_product_id:id,p_quantity:Math.max(1,Number(quantity)),p_note:note||null})}
export async function loadSellerInventoryMovements(productId=null){if(!uid())return [];const sid=productId?`&product_id=eq.${encodeURIComponent(productId)}`:'';return await rest(`inventory_movements?select=id,product_id,movement_type,quantity_delta,stock_before,stock_after,note,created_at&order=created_at.desc${sid}`)||[]}
export async function moderateProduct(id,status,reason=''){if(!uid())return null;return await rpc('moderate_product',{p_product_id:id,p_status:status,p_reason:reason||null})}
export async function moderateStore(id,status){if(!uid())return null;return await rpc('moderate_store',{p_store_id:id,p_status:status})}
export function startCommercialSync(catalogProvider=()=>[]){let timer;const run=async()=>{if(!uid())return;const catalog=catalogProvider()||[],fav=read('vanidaxi-favorites',[]),cart=read('vanidaxi-cart',[]),addr=read('vanidaxi-address',null);try{await syncProfile();await Promise.all([syncFavorites(fav),syncCart(cart,catalog),addr?syncAddress(addr):Promise.resolve()]);localStorage.setItem('vanidaxi-commercial-catalog',JSON.stringify(catalog))}catch(e){console.warn('[VaniDaxi commercial sync]',e.message)}};const schedule=()=>{clearTimeout(timer);timer=setTimeout(run,700)};if(!window.__vaniCommercialPatched){const original=localStorage.setItem.bind(localStorage);localStorage.setItem=(k,v)=>{original(k,v);if(['vanidaxi-favorites','vanidaxi-cart','vanidaxi-address'].includes(k))schedule()};window.__vaniCommercialPatched=true}run();return()=>clearTimeout(timer)}