import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,Check,Clock3,MapPin,Package,RefreshCw,Truck,UserRound,ShieldCheck}from'lucide-react'
import{getMySellerStore,loadCommercialState,loadOrderDeliveryEvents,updateOrderDelivery}from'./commercialApi.js'
import'./logistics-dashboard.css'
const URL='https://oycwqpqoxgohzqivclzd.supabase.co',KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpY'
const session=()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-auth-session')||'null')}catch{return null}}
const money=v=>`$${Number(v||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const date=v=>v?new Date(v).toLocaleString('es-MX',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'
const statusLabel=s=>({pending:'Pendiente',preparing:'Preparando',awaiting_vanidaxi:'Listo para entrega a VaniDaxi',received_by_vanidaxi:'Recibido por VaniDaxi',in_transit:'En camino',delivered:'Entregado',failed:'Incidencia',cancelled:'Cancelado',processing:'Preparando',ready:'Listo para entrega',shipped:'En camino',out_for_delivery:'En reparto'}[String(s||'').toLowerCase()]||s||'Sin estado')
const normalizeStatus=s=>({processing:'preparing',ready:'awaiting_vanidaxi',shipped:'in_transit',out_for_delivery:'in_transit'}[String(s||'').toLowerCase()]||String(s||'').toLowerCase()||'preparing')
const statusForOrder=o=>{const x=String(o||'').toLowerCase();return x==='paid'||x==='processing'?'preparing':x==='shipped'?'in_transit':x==='delivered'?'delivered':x==='cancelled'?'cancelled':'preparing'}
const adminStatuses=['preparing','awaiting_vanidaxi','received_by_vanidaxi','in_transit','delivered','failed','cancelled']
const sellerStatuses=(provider)=>provider==='vanidaxi'?['preparing','awaiting_vanidaxi']:['preparing','in_transit','delivered']
async function rest(path,token){const r=await fetch(`${URL}/rest/v1/${path}`,{headers:{apikey:KEY,Authorization:`Bearer ${token||KEY}`}});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.message||`Supabase ${r.status}`);return d}
export default function LogisticsDashboard({back}){
 const s=session()
 const[profile,setProfile]=useState(null),[orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState({status:'preparing',tracking:'',notes:''})
 const admin=profile?.role==='admin',seller=profile?.role==='seller'
 const load=async()=>{setLoading(true);setError('');try{const state=await loadCommercialState();const mine=state?.orders||[];setProfile(state?.profile||null);if(state?.profile?.role==='admin'){const rows=await rest('orders?select=id,order_number,status,total,shipping_address,payment_provider,delivery_provider,delivery_status,delivery_tracking,delivery_notes,delivery_custody,delivery_updated_at,delivery_handoff_at,delivery_received_at,delivered_at,created_at&order=created_at.desc&limit=300',s?.access_token);setOrders(rows||[])}else if(state?.profile?.role==='seller'){const store=await getMySellerStore();const sid=encodeURIComponent(store?.id||'');if(!store?.id){setOrders([]);return}const items=await rest(`order_items?select=order_id,seller_id&seller_id=eq.${sid}&limit=500`,s?.access_token);const ids=[...new Set((items||[]).map(x=>x.order_id).filter(Boolean))];const rows=ids.length?await rest(`orders?select=id,order_number,status,total,shipping_address,payment_provider,delivery_provider,delivery_status,delivery_tracking,delivery_notes,delivery_custody,delivery_updated_at,delivery_handoff_at,delivery_received_at,delivered_at,created_at&id=in.(${ids.map(encodeURIComponent).join(',')})&order=created_at.desc`,s?.access_token):[];setOrders(rows||[])}else setOrders(mine)}catch(e){setError(e.message||'No se pudo cargar logística.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const current=selected||orders[0]||null
 useEffect(()=>{if(!current){setEvents([]);return}let alive=true;(async()=>{try{const e=await loadOrderDeliveryEvents(current.id);if(alive)setEvents(e)}catch{if(alive)setEvents([])}})();setForm({status:normalizeStatus(current.delivery_status||statusForOrder(current.status)),tracking:current.delivery_tracking||'',notes:current.delivery_notes||''});return()=>{alive=false}},[current?.id,current?.delivery_status,current?.status,current?.delivery_provider])
 const stats=useMemo(()=>({total:orders.length,active:orders.filter(o=>!['delivered','cancelled','returned'].includes(normalizeStatus(o.delivery_status||statusForOrder(o.status)))).length,inTransit:orders.filter(o=>['in_transit'].includes(normalizeStatus(o.delivery_status||statusForOrder(o.status)))).length,delivered:orders.filter(o=>normalizeStatus(o.delivery_status||statusForOrder(o.status))==='delivered').length}),[orders])
 const save=async()=>{if(!current)return;setBusy(true);setError('');setNotice('');try{await updateOrderDelivery(current.id,form.status,form.tracking||null,form.notes||null);setNotice('Estado logístico actualizado.');await load();const e=await loadOrderDeliveryEvents(current.id);setEvents(e)}catch(e){setError(e.message||'No se pudo actualizar el envío.')}finally{setBusy(false)}}
 if(loading)return <div className="logistics-screen"><div className="logistics-loading"><RefreshCw className="spin"/>Cargando VaniDaxi Logistics…</div></div>
 if(!s?.user)return <div className="logistics-screen"><div className="logistics-empty"><ShieldCheck size={44}/><h1>Inicia sesión</h1><p>La trazabilidad de tus pedidos requiere una cuenta VaniDaxi.</p><button onClick={back}>Volver</button></div></div>
 const options=admin?adminStatuses:seller?sellerStatuses(current?.delivery_provider):[]
 return <div className="logistics-screen"><header className="logistics-top"><div><button className="logistics-back" onClick={back}><ArrowLeft size={16}/>VaniDaxi</button><span>VANIDAXI LOGISTICS</span><h1>{admin?'Centro de control logístico':seller?'Despachos de tu tienda':'Seguimiento de mis pedidos'}</h1><p>{admin?'Supervisa estados, trazabilidad y custodia de todas las entregas.':seller?'Prepara y actualiza la entrega de los pedidos asociados a tu tienda.':'Consulta el estado real de cada pedido y su historial de movimientos.'}</p></div><button className="logistics-refresh" onClick={load}><RefreshCw size={16}/>Actualizar</button></header>
 <section className="logistics-kpis"><article><Package/><small>Pedidos</small><b>{stats.total}</b></article><article><Clock3/><small>En operación</small><b>{stats.active}</b></article><article><Truck/><small>En camino</small><b>{stats.inTransit}</b></article><article><Check/><small>Entregados</small><b>{stats.delivered}</b></article></section>
 {error&&<div className="logistics-error">{error}</div>}{notice&&<div className="logistics-notice">{notice}</div>}
 <main className="logistics-grid"><section className="logistics-card"><div className="logistics-card-head"><div><small>OPERACIÓN</small><h2>Pedidos</h2></div></div>{orders.length?orders.map(o=><button key={o.id} className={`logistics-order ${current?.id===o.id?'active':''}`} onClick={()=>setSelected(o)}><div><b>#{o.order_number||o.id.slice(0,8)}</b><small>{date(o.created_at)} · {money(o.total)}</small></div><span>{statusLabel(o.delivery_status||statusForOrder(o.status))}</span></button>):<div className="logistics-empty-inline">No hay pedidos disponibles.</div>}</section>
 <section className="logistics-card logistics-detail">{current?<><div className="logistics-card-head"><div><small>TRAZABILIDAD</small><h2>#{current.order_number||current.id.slice(0,8)}</h2></div><span className="logistics-badge">{statusLabel(current.delivery_status||statusForOrder(current.status))}</span></div><div className="tracking-meta"><div><MapPin/><span><b>Destino</b><small>{formatAddress(current.shipping_address)}</small></span></div><div><UserRound/><span><b>Proveedor logístico</b><small>{current.delivery_provider||'VaniDaxi Logistics'}</small></span></div><div><Package/><span><b>Guía</b><small>{current.delivery_tracking||'Aún no asignada'}</small></span></div></div><div className="timeline">{adminStatuses.slice(0,5).map((st,i)=>{const currentStep=normalizeStatus(current.delivery_status||statusForOrder(current.status));const orderSteps=['preparing','awaiting_vanidaxi','received_by_vanidaxi','in_transit','delivered'];const active=currentStep?orderSteps.indexOf(currentStep)>=i:false;return <div className={active?'done':''} key={st}><i>{active?<Check size={13}/>:i+1}</i><span><b>{statusLabel(st)}</b><small>{active&&events.find(e=>normalizeStatus(e.status)===st)?date(events.find(e=>normalizeStatus(e.status)===st).created_at):'Pendiente'}</small></span></div>})}</div>{(admin||seller)&&<div className="logistics-editor"><h3>Actualizar operación</h3><div className="logistics-form-grid"><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{options.map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label><label>Guía<input value={form.tracking} onChange={e=>setForm({...form,tracking:e.target.value})} placeholder="Ej. VD-2026-000123"/></label></div><label>Nota operativa<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Nota visible para operación y seguimiento"/></label><button className="logistics-save" disabled={busy} onClick={save}>{busy?<RefreshCw className="spin"/>:<Check/>}{busy?'Guardando…':'Guardar actualización'}</button></div>}<div className="event-list"><h3>Historial de movimientos</h3>{events.length?events.map(e=><div key={e.id}><i><Check size={13}/></i><span><b>{statusLabel(e.status)}</b><small>{date(e.created_at)}{e.tracking?` · ${e.tracking}`:''}</small>{e.notes&&<em>{e.notes}</em>}</span></div>):<p>Aún no hay eventos de trazabilidad registrados.</p>}</div></>:<div className="logistics-empty"><Package size={42}/><h2>Selecciona un pedido</h2><p>La trazabilidad aparecerá aquí.</p></div>}</section></main></div>
}
function formatAddress(a){if(!a)return'No disponible';if(typeof a==='string')return a;return [a.full_name,a.address_line1||a.street,a.address_line2,a.city,a.state,a.postal_code||a.zip,a.country].filter(Boolean).join(', ')}