import React,{useMemo,useState}from'react'
import{Lock,ShieldCheck,ArrowLeft,CheckCircle2}from'lucide-react'
import{updatePassword}from'./auth.js'
import'./auth-choice.css'
const MIN=8
const checksFor=p=>({length:p.length>=MIN,letter:/[A-Za-zÁÉÍÓÚáéíóúÑñ]/.test(p),number:/\d/.test(p),special:/[^A-Za-z0-9ÁÉÍÓÚáéíóúÑñ]/.test(p)})
export default function PasswordRecovery({onDone}){
 const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const checks=useMemo(()=>checksFor(password),[password]),valid=Object.values(checks).every(Boolean)&&password===confirm
 const submit=async e=>{e.preventDefault();setError('');setMessage('');if(!Object.values(checks).every(Boolean)){setError('La contraseña debe tener al menos 8 caracteres, una letra, un número y un carácter especial.');return}if(password!==confirm){setError('Las contraseñas no coinciden.');return}setLoading(true);try{await updatePassword(password);setMessage('Contraseña actualizada correctamente.');setTimeout(()=>onDone?.(),900)}catch(err){setError(err?.message||'No fue posible actualizar la contraseña.')}finally{setLoading(false)}}
 return <div className="auth-modal" role="dialog" aria-modal="true" aria-label="Restablecer contraseña"><div className="auth-card"><button className="auth-close" onClick={onDone} aria-label="Cerrar"><ArrowLeft size={20}/></button><div className="auth-header"><div className="auth-badge"><ShieldCheck size={20}/></div><h2>Restablecer contraseña</h2><p>Elige una nueva contraseña para proteger tu cuenta VaniDaxi.</p></div><form onSubmit={submit} className="auth-form"><label><span>Nueva contraseña</span><div className="auth-input-wrap"><Lock size={18}/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="new-password" placeholder="Nueva contraseña" required/></div></label><div className="password-guidance" aria-live="polite"><strong>Requisitos de contraseña</strong><div className={checks.length?'ok':''}>• Mínimo 8 caracteres</div><div className={checks.letter?'ok':''}>• Al menos una letra</div><div className={checks.number?'ok':''}>• Al menos un número</div><div className={checks.special?'ok':''}>• Al menos un carácter especial</div><small>Se permiten letras, números, puntos, guiones, guion bajo y otros caracteres especiales.</small></div><label><span>Confirmar contraseña</span><div className="auth-input-wrap"><CheckCircle2 size={18}/><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" autoComplete="new-password" placeholder="Repite la contraseña" required/></div></label>{error&&<div className="auth-error" role="alert">{error}</div>}{message&&<div className="auth-message" role="status">{message}</div>}<button className="auth-primary" disabled={loading||!valid}>{loading?'Actualizando…':'Guardar nueva contraseña'}</button></form></div></div>
}
