import React,{useEffect,useMemo,useState}from'react'
import{Star,Send,MessageCircle}from'lucide-react'
import{loadProductReviews,createReview}from'./commercialApi.js'
import './product-reviews.css'
export default function ProductReviews({product,orders=[]}){
 const[rows,setRows]=useState([]),[rating,setRating]=useState(0),[comment,setComment]=useState(''),[sending,setSending]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{if(product?.id)loadProductReviews(product.id).then(setRows).catch(()=>setRows([]))},[product?.id])
 const eligible=useMemo(()=>orders.find(o=>o.status==='delivered'&&(o.items||[]).some(i=>String(i.product_id||i.product?.id)===String(product?.id))),[orders,product?.id])
 const reviewed=useMemo(()=>rows.some(r=>eligible&&String(r.order_id)===String(eligible.id)),[rows,eligible])
 const average=rows.length?rows.reduce((a,r)=>a+Number(r.rating||0),0)/rows.length:0
 async function submit(){if(!eligible||!rating||sending)return;setSending(true);setMessage('');try{const r=await createReview({product_id:product.id,order_id:eligible.id,rating,title:null,comment:comment.trim()||null});if(r){setRows(x=>[r,...x]);setRating(0);setComment('');setMessage('Tu reseña fue registrada correctamente.')}else setMessage('No se pudo registrar la reseña.')}catch(e){setMessage('Solo puedes calificar una compra entregada y una vez por compra.')}finally{setSending(false)}}
 return <section className="product-reviews"><div className="reviews-heading"><div><span>OPINIONES</span><h2>Reseñas y calificaciones</h2></div><div className="review-summary"><b>{average?average.toFixed(1):'—'}</b><div>{[1,2,3,4,5].map(n=><Star key={n} size={14} fill={n<=Math.round(average)?'currentColor':'none'}/>)}</div><small>{rows.length} reseña{rows.length===1?'':'s'}</small></div></div>{eligible&&!reviewed&&<div className="review-form"><b>¿Ya recibiste este producto?</b><small>Solo compradores con una entrega confirmada pueden calificar.</small><div className="review-stars">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} aria-label={`${n} estrellas`}><Star size={25} fill={n<=rating?'currentColor':'none'}/></button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="Cuéntanos tu experiencia (opcional)"/><button className="review-send" disabled={!rating||sending} onClick={submit}><Send size={16}/>{sending?'Enviando…':'Publicar reseña'}</button>{message&&<small className="review-message">{message}</small>}</div>}{rows.length?<div className="reviews-list">{rows.map(r=><article className="review-item" key={r.id}><div className="review-item-top"><span>{[1,2,3,4,5].map(n=><Star key={n} size={14} fill={n<=Number(r.rating)?'currentColor':'none'}/>)}</span><small>{new Date(r.created_at).toLocaleDateString('es-MX')}</small></div>{r.comment&&<p>{r.comment}</p>}<b>Compra verificada</b></article>)}</div>:<div className="reviews-empty"><MessageCircle size={22}/><span>Aún no hay reseñas para este producto.</span></div>}</section>
}