import { supabase } from './supabaseClient.js'

const API='https://oycwqpqoxgohzqivclzd.supabase.co'
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpYj'
const AUTH='vanidaxi-auth-session'
const readSession=()=>{try{return JSON.parse(localStorage.getItem(AUTH)||'null')}catch{return null}}
const token=()=>readSession()?.access_token||''
const uid=()=>readSession()?.user?.id||''
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const rest=async(path,options={})=>{const r=await fetch(`${API}/rest/v1/${path}`,{...options,headers:{apikey:KEY,Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error(await r.text().catch(()=>`Supabase ${r.status}`));return r.status===204?null:r.json().catch(()=>null)}

let overlay=null
const close=()=>{overlay?.remove();overlay=null}
const shell=(body)=>{close();overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;background:rgba(15,23,42,.42);backdrop-filter:blur(5px);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px;font-family:inherit';overlay.innerHTML=`<div style="width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:26px;padding:26px;box-shadow:0 24px 70px rgba(0,0,0,.2)"><div style="display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px"><div><small style="letter-spacing:.14em;color:#64748b;font-weight:700">MI CUENTA</small><h2 style="margin:6px 0 0;font-size:28px">Perfil</h2><p style="margin:7px 0 0;color:#64748b">Administra tus datos personales.</p></div><button data-close aria-label="Cerrar" style="border:0;background:#f1f5f9;border-radius:12px;width:42px;height:42px;font-size:22px;cursor:pointer">×</button></div>${body}</div>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-close]'))close()});return overlay}
const field=(label,id,value,type='text',extra='')=>`<label style="display:block;margin:14px 0"><span style="display:block;font-size:13px;font-weight:700;margin-bottom:7px;color:#334155">${label}</span><input id="${id}" type="${type}" value="${esc(value)}" ${extra} style="box-sizing:border-box;width:100%;padding:13px 14px;border:1px solid #cbd5e1;border-radius:13px;font:inherit;outline:none"></label>`
const primary='style="width:100%;border:0;border-radius:13px;padding:14px 16px;background:#111827;color:white;font-weight:700;cursor:pointer"'

async function profile(){
 const s=readSession();if(!s?.user){shell('<p style="color:#64748b">Necesitas iniciar sesión para administrar tu perfil.</p>');return}
 let p=null;try{const rows=await rest(`profiles?select=id,full_name,username,avatar_url,phone,role,is_active& id=eq.${encodeURIComponent(uid())}`.replace('& id=','&id='));p=rows?.[0]||null}catch(e){console.warn('[VaniDaxi profile]',e)}
 const m=s.user?.user_metadata||{}
 const el=shell(`<div style="display:grid;grid-template-columns:1fr 1fr;gap:0 16px"><div>${field('Nombre completo','vd-profile-name',p?.full_name||m.name||'')}</div><div>${field('Nombre de usuario','vd-profile-username',p?.username||'')}</div></div>${field('Teléfono','vd-profile-phone',p?.phone||'','tel')}${field('Correo electrónico','vd-profile-email',s.user?.email||'','email','readonly')}<p style="margin:5px 0 18px;color:#64748b;font-size:12px">El correo pertenece a tu cuenta de acceso. Para cambiarlo se requiere un proceso de confirmación.</p><button id="vd-profile-save" ${primary}>Guardar cambios</button><p id="vd-profile-msg" style="min-height:20px;margin:10px 0 0;color:#64748b;font-size:13px"></p>`)
 el.querySelector('#vd-profile-save').addEventListener('click',async()=>{const name=el.querySelector('#vd-profile-name').value.trim(),username=el.querySelector('#vd-profile-username').value.trim(),phone=el.querySelector('#vd-profile-phone').value.trim()||null,msg=el.querySelector('#vd-profile-msg'),btn=el.querySelector('#vd-profile-save');if(!name){msg.textContent='Escribe tu nombre completo.';return}if(username.length>0&&!/^[a-zA-Z0-9_.-]{3,30}$/.test(username)){msg.textContent='El nombre de usuario debe tener 3–30 caracteres y solo letras, números, punto, guion o guion bajo.';return}btn.disabled=true;btn.style.opacity='.65';msg.textContent='Guardando…';try{await rest(`profiles?id=eq.${encodeURIComponent(uid())}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({full_name:name,username:username||null,phone})});const next={...s,user:{...s.user,user_metadata:{...m,name}}};localStorage.setItem(AUTH,JSON.stringify({...s,user:next.user}));msg.textContent='Perfil actualizado correctamente.';setTimeout(close,700)}catch(err){console.error('[VaniDaxi profile]',err);const text=String(err?.message||'');msg.textContent=text.toLowerCase().includes('duplicate')||text.toLowerCase().includes('unique')?'Ese nombre de usuario ya está en uso.':'No se pudo guardar el perfil. Intenta nuevamente.';btn.disabled=false;btn.style.opacity='1'}})
}

function bind(){document.querySelectorAll('.profile-links').forEach(box=>{if(box.dataset.vdProfileBound)return;const buttons=[...box.querySelectorAll('button')];if(!buttons.length)return;const b=document.createElement('button');b.innerHTML='<span style="font-size:20px">👤</span><span><b style="display:block">Perfil</b><small style="display:block;color:#64748b;margin-top:3px">Administra tus datos personales</small></span>';b.style.cssText='display:flex;align-items:center;gap:12px;text-align:left;width:100%;border:1px solid #e2e8f0;background:#fff;border-radius:14px;padding:14px 15px;cursor:pointer;font:inherit;color:#0f172a';b.addEventListener('click',e=>{e.preventDefault();profile()});box.insertBefore(b,box.firstChild);box.dataset.vdProfileBound='1'})}
const observer=new MutationObserver(bind)
observer.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind()
