/* VaniDaxi — PWA, permisos, instalación, búsqueda con foto y formas de pago */
(() => {
  const S={install:'vanidaxi-install-dismissed',setup:'vanidaxi-permissions-setup'}
  const standalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true
  try{const k='vanidaxi-address',r=localStorage.getItem(k);if(!r)localStorage.setItem(k,JSON.stringify({name:'Mi cuenta',street:'',city:'',zip:''}));else{const d=JSON.parse(r);if(d&&typeof d==='object'){d.name='Mi cuenta';localStorage.setItem(k,JSON.stringify(d))}}}catch(_){ }
  try{if(!navigator.share)Object.defineProperty(navigator,'share',{configurable:true,value:({title='VaniDaxi',text=''})=>{const v=text||title;if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(v);const a=document.createElement('textarea');a.value=v;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{document.execCommand('copy')}finally{a.remove()}return Promise.resolve()}})}catch(_){ }
  const css=document.createElement('style');css.textContent=`.vd-overlay{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:22px;background:rgba(32,20,45,.48);backdrop-filter:blur(7px);font-family:Inter,system-ui,sans-serif}.vd-modal{width:min(430px,100%);background:#fff;border-radius:28px;padding:25px;box-shadow:0 24px 70px rgba(40,20,60,.25);color:#29222f}.vd-brand{display:flex;align-items:center;gap:10px;font-size:22px;font-weight:800;color:#70429a}.vd-brand img{width:38px;height:38px}.vd-modal h2{margin:18px 0 8px;font-size:24px}.vd-modal p{margin:0 0 18px;line-height:1.5;color:#665c6d;font-size:14px}.vd-primary{width:100%;border:0;border-radius:16px;padding:14px 18px;background:linear-gradient(135deg,#70429a,#c45aa5);color:#fff;font-weight:800;font-size:15px;cursor:pointer}.vd-secondary{width:100%;border:0;background:transparent;padding:12px;color:#756a7c;font-weight:700;cursor:pointer}.vd-permission{display:flex;align-items:center;gap:13px;padding:14px 0;border-top:1px solid #eee8f1}.vd-permission-icon{width:42px;height:42px;border-radius:14px;background:#f5edf9;display:grid;place-items:center;font-size:20px;flex:none}.vd-permission b{display:block;font-size:14px}.vd-permission span{display:block;font-size:12px;color:#756a7c;margin-top:3px}.vd-camera-btn{border:0;background:#f3eafa;color:#70429a;border-radius:14px;height:44px;width:46px;display:grid;place-items:center;cursor:pointer;flex:none}.vd-camera-btn svg{width:20px;height:20px}.vd-photo-input{display:none}.vd-photo-preview{font-size:11px;color:#70429a;margin:4px 0 0 8px}.vd-pay-list{display:grid;gap:10px;margin-top:14px}.vd-pay-option{display:flex;align-items:center;gap:12px;width:100%;padding:14px;border:1px solid #e7ddea;border-radius:17px;background:#fff;color:#2d2633;text-align:left;cursor:pointer}.vd-pay-option.active{border-color:#70429a;background:#f8f2fb;box-shadow:0 0 0 2px rgba(112,66,154,.08)}.vd-pay-icon{width:40px;height:40px;border-radius:12px;background:#f2e8f8;display:grid;place-items:center;font-size:19px;flex:none}.vd-pay-copy{display:flex;flex-direction:column;gap:3px;min-width:0}.vd-pay-copy b{font-size:14px}.vd-pay-copy span{font-size:11px;color:#756a7c;line-height:1.35}.vd-pay-check{margin-left:auto;color:#70429a;font-weight:900;font-size:17px}.vd-pay-note{margin:12px 0 0;font-size:11px;color:#756a7c;line-height:1.45}`;document.head.appendChild(css)
  const close=e=>e?.remove(), modal=(html,ready)=>{if(document.querySelector('.vd-overlay'))return;const e=document.createElement('div');e.className='vd-overlay';e.innerHTML=`<div class="vd-modal">${html}</div>`;document.body.appendChild(e);ready?.(e)}
  function install(){if(standalone()||!window.__vanidaxiDeferredPrompt||localStorage.getItem(S.install))return;modal(`<div class="vd-brand"><img src="./logo.svg" alt="VaniDaxi"/> VaniDaxi</div><h2>Instala VaniDaxi</h2><p>Ten VaniDaxi siempre a la mano, con una experiencia rápida y cómoda desde tu teléfono.</p><button class="vd-primary" data-i>Instalar aplicación</button><button class="vd-secondary" data-l>Ahora no</button>`,e=>{e.querySelector('[data-i]').onclick=async()=>{const p=window.__vanidaxiDeferredPrompt;if(!p)return close(e);p.prompt();try{await p.userChoice}catch(_){}window.__vanidaxiDeferredPrompt=null;close(e)};e.querySelector('[data-l]').onclick=()=>{localStorage.setItem(S.install,'1');close(e)}})}
  async function permissions(){if(!standalone()||localStorage.getItem(S.setup))return;modal(`<div class="vd-brand"><img src="./logo.svg" alt="VaniDaxi"/> VaniDaxi</div><h2>Configura tu experiencia</h2><p>Activa las funciones que quieras usar. Si rechazas algún permiso, podrás seguir usando VaniDaxi.</p><div class="vd-permission"><div class="vd-permission-icon">🔔</div><div><b>Notificaciones</b><span>Pedidos, mensajes y novedades.</span></div></div><div class="vd-permission"><div class="vd-permission-icon">📍</div><div><b>Ubicación</b><span>Entregas y servicios cercanos.</span></div></div><div class="vd-permission"><div class="vd-permission-icon">📷</div><div><b>Cámara</b><span>Busca productos usando una foto.</span></div></div><button class="vd-primary" data-c>Continuar</button><button class="vd-secondary" data-s>Ahora no</button>`,e=>{e.querySelector('[data-c]').onclick=async()=>{close(e);if('Notification'in window&&Notification.permission==='default')try{await Notification.requestPermission()}catch(_){}if(navigator.geolocation)try{await new Promise(r=>navigator.geolocation.getCurrentPosition(r,r,{timeout:8000,maximumAge:300000}))}catch(_){}localStorage.setItem(S.setup,'1')};e.querySelector('[data-s]').onclick=()=>{localStorage.setItem(S.setup,'1');close(e)}})}
  function photoSearch(){[...document.querySelectorAll('input[type="text"],input[type="search"]')].filter(i=>/buscar|search/i.test(i.placeholder||'')&&!i.dataset.vdPhoto).forEach(input=>{input.dataset.vdPhoto='1';const wrap=input.parentElement;if(!wrap)return;const b=document.createElement('button');b.type='button';b.className='vd-camera-btn';b.title='Buscar con foto';b.setAttribute('aria-label','Buscar con foto');b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h3l1.5-2h7L17 7h3v11H4z"/><circle cx="12" cy="12" r="3.5"/></svg>';const f=document.createElement('input');f.type='file';f.accept='image/*';f.capture='environment';f.className='vd-photo-input';b.onclick=()=>f.click();f.onchange=()=>{const p=f.files?.[0];if(!p)return;input.value='Buscar con foto';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));const old=document.querySelector('.vd-photo-preview');old?.remove();const x=document.createElement('div');x.className='vd-photo-preview';x.textContent=`📷 Foto lista para buscar: ${p.name}`;wrap.parentElement?.appendChild(x);setTimeout(()=>x.remove(),4500)};wrap.classList.add('vd-camera-wrap');wrap.appendChild(b);wrap.appendChild(f)})}
  function paymentMethods(){
    const modals=[...document.querySelectorAll('.account-modal')];
    const modalEl=modals.find(m=>/Métodos de pago/i.test(m.querySelector('.modal-head h2')?.textContent||''));
    if(!modalEl||modalEl.dataset.vdPayments==='1')return;
    const body=modalEl.querySelector('.modal-body');
    if(!body)return;
    modalEl.dataset.vdPayments='1';
    const saved=(()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-payment')||'null')||{method:'Tarjeta',detail:''}}catch{return{method:'Tarjeta',detail:''}}})();
    const current=(saved.method||'Tarjeta').toLowerCase();
    body.innerHTML=`<div class="saved-payment" style="display:flex;align-items:center;gap:12px"><div style="width:42px;height:42px;border-radius:13px;background:#f2e8f8;display:grid;place-items:center;font-size:19px">💳</div><div><b>Formas de pago</b><small style="display:block;color:#756a7c;margin-top:3px">Elige cómo quieres pagar tus compras.</small></div></div><div class="vd-pay-list"><button class="vd-pay-option ${current==='stripe'||current==='tarjeta'?'active':''}" data-pay="Tarjeta"><div class="vd-pay-icon">💳</div><div class="vd-pay-copy"><b>Tarjeta</b><span>Pago seguro mediante Stripe Checkout.</span></div><span class="vd-pay-check">${current==='stripe'||current==='tarjeta'?'✓':''}</span></button><button class="vd-pay-option ${current==='oxxo'?'active':''}" data-pay="OXXO"><div class="vd-pay-icon">🧾</div><div class="vd-pay-copy"><b>OXXO</b><span>Genera tu referencia de pago mediante Stripe.</span></div><span class="vd-pay-check">${current==='oxxo'?'✓':''}</span></button><button class="vd-pay-option ${current==='transferencia'?'active':''}" data-pay="Transferencia"><div class="vd-pay-icon">🏦</div><div class="vd-pay-copy"><b>Transferencia bancaria</b><span>Inicia la transferencia bancaria mediante Stripe.</span></div><span class="vd-pay-check">${current==='transferencia'?'✓':''}</span></button></div><p class="vd-pay-note">Tu selección queda guardada en este dispositivo y se envía a Stripe al iniciar el pago.</p><button class="modal-primary" data-pay-save style="margin-top:8px">Guardar forma de pago</button>`;
    let selected=saved.method||'Tarjeta';
    const refresh=()=>body.querySelectorAll('[data-pay]').forEach(b=>{const active=b.dataset.pay.toLowerCase()===String(selected).toLowerCase();b.classList.toggle('active',active);const c=b.querySelector('.vd-pay-check');if(c)c.textContent=active?'✓':''});
    body.querySelectorAll('[data-pay]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.pay;refresh()}));
    body.querySelector('[data-pay-save]')?.addEventListener('click',()=>{try{localStorage.setItem('vanidaxi-payment-method',selected);localStorage.setItem('vanidaxi-payment',JSON.stringify({method:selected,detail:''}))}catch(_){};const notice=document.createElement('div');notice.className='vd-pay-note';notice.textContent='Forma de pago guardada correctamente.';body.querySelector('.vd-pay-note')?.remove();body.appendChild(notice)});
  }
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.__vanidaxiDeferredPrompt=e;setTimeout(install,500)});window.addEventListener('appinstalled',()=>{window.__vanidaxiDeferredPrompt=null;setTimeout(permissions,800)});window.addEventListener('load',()=>setTimeout(()=>{install();permissions();photoSearch();paymentMethods()},900));new MutationObserver(()=>{photoSearch();paymentMethods()}).observe(document.documentElement,{childList:true,subtree:true})
})()
