import React,{useEffect,useMemo,useState}from'react';
import{ChevronLeft,RefreshCw,Store,Package,ShoppingBag,DollarSign,TrendingUp,Users,AlertCircle,BarChart3,Boxes,Settings,Clock,CheckCircle2,ArrowUpRight}from'lucide-react';
import'./seller-dashboard.css';
const URL='https://oycwqpqoxgohzqivclzd.supabase.co';
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpY';
const session=()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-auth-session')||'null')}catch{return null}};
const money=n=>`$${Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function rest(path){const s=session(),t=s?.access_token;const r=await fetch(`${URL}/rest/v1/${path}`,{headers:{apikey:KEY,Authorization:`Bearer ${t||KEY}`}});if(!r.ok)throw Error(await r.text());return r.json()}
const validStatuses=new Set(['paid','processing','shipped','delivered']);
export default function SellerDashboard({go}){
 const[data,setData]=useState({store:null,products:[],items:[],orders:[],customers:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('resumen');
 const load=async()=>{setLoading(true);setError('');try{const owner=session()?.user?.id;if(!owner)throw Error('Inicia sesión para acceder al panel de vendedor.');const profiles=await rest(`profiles?select=id,full_name,role&id=eq.${encodeURIComponent(owner)}&limit=1`);if(profiles?.[0]?.role!=='seller')throw Error('Esta sección está disponible para cuentas de vendedor.');const stores=await rest(`seller_stores?select=id,owner_id,store_name,description,status&id=eq.${encodeURIComponent(owner)}&limit=1`).catch(()=>[]);const store=stores?.[0]||null;if(!store){setData({store:null,products:[],items:[],orders:[],customers:[]});return}const sid=encodeURIComponent(store.id);const products=await rest(`products?select=id,name,price,cost_price,stock,status,created_at,category_id&seller_id=eq.${sid}&order=created_at.desc`).catch(()=>[]);const items=await rest(`order_items?select=id,order_id,product_id,product_name,quantity,unit_price,total_price,created_at&seller_id=eq.${sid}&order=created_at.desc`).catch(()=>[]);const ids=[...new Set(items.map(x=>x.order_id).filter(Boolean))];const orders=ids.length?await rest(`orders?select=id,order_number,user_id,status,total,created_at&id=in.(${ids.map(encodeURIComponent).join(',')})&order=created_at.desc`).catch(()=>[]):[];const customers=[...new Set(orders.map(x=>x.user_id).filter(Boolean))];setData({store,products,items,orders,customers})}catch(e){setError(e?.message||'No fue posible cargar el panel.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const orderMap=new Map(data.orders.map(o=>[o.id,o]));const items=data.items.filter(x=>validStatuses.has(orderMap.get(x.order_id)?.status));const revenue=items.reduce((a,x)=>a+Number(x.total_price||0),0);const cost=items.reduce((a,x)=>{const p=data.products.find(p=>p.id===x.product_id);return a+Number(p?.cost_price||0)*Number(x.quantity||0)},0);const units=items.reduce((a,x)=>a+Number(x.quantity||0),0);const orders=new Set(items.map(x=>x.order_id)).size;return{revenue,cost,profit:revenue-cost,units,orders,avg:orders?revenue/orders:0,customers:new Set(data.orders.filter(o=>validStatuses.has(o.status)).map(o=>o.user_id).filter(Boolean)).size}},[data]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(Date.now()-(6-i)*86400000),key=d.toISOString().slice(0,10);const value=data.items.filter(x=>x.created_at?.slice(0,10)===key).reduce((a,x)=>a+Number(x.total_price||0),0);return{label:d.toLocaleDateString('es-MX',{weekday:'short'}).replace('.',''),value}}),[data.items]);
 const topProducts=useMemo(()=>{const m=new Map();for(const x of data.items){const a=m.get(x.product_id)||{name:x.product_name,units:0,revenue:0};a.units+=Number(x.quantity||0);a.revenue+=Number(x.total_price||0);m.set(x.product_id,a)}return[...m.values()].sort((a,b)=>b.units-a.units).slice(0,5)},[data.items]);
 const low=data.products.filter(p=>Number(p.stock||0)<=5&&p.status!=='inactive'),pending=data.products.filter(p=>p.status==='pending');
 const nav=[['resumen','Resumen',BarChart3],['productos','Productos',Package],['pedidos','Pedidos',ShoppingBag],['ingresos','Ingresos',DollarSign],['inventario','Inventario',Boxes],['clientes','Clientes',Users],['configuracion','Tienda',Settings]];
 if(loading)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><RefreshCw/><h2>Cargando análisis…</h2><p>Consultando ventas, productos e ingresos reales.</p></div></main>;
 if(error)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><AlertCircle/><h2>No disponible</h2><p>{error}</p><button onClick={()=>go('profile')}>Volver a mi cuenta</button></div></main>;
 if(!data.store)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><Store/><h2>Tu tienda aún no está creada</h2><p>Cuando tu registro como vendedor sea aprobado, aquí aparecerán tus métricas y operaciones.</p><button onClick={()=>go('profile')}>Volver a mi cuenta</button></div></main>;
 return <main className="scroll-page seller-dashboard"><header className="seller-top"><button className="icon-btn" onClick={()=>go('profile')}><ChevronLeft size={18}/></button><div><span>VaniDaxi · Vendedor</span><h1>{data.store.store_name}</h1></div><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={16}/></button></header>
 <section className="seller-welcome"><div><small>Panel de control</small><h2>Resumen de tu negocio</h2><p>Datos conectados a tus productos y ventas.</p></div><span className="store-status"><CheckCircle2 size={13}/> {data.store.status==='approved'?'Activa':data.store.status}</span></section>
 <nav className="seller-tabs">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={14}/>{label}</button>)}</nav>
 {tab==='resumen'&&<><div className="seller-stats"><Stat I={DollarSign} label="Ingresos" value={money(stats.revenue)}/><Stat I={TrendingUp} label="Ganancia" value={money(stats.profit)} hint={stats.cost?'Costo registrado':'Sin costos aún'}/><Stat I={ShoppingBag} label="Pedidos" value={stats.orders}/><Stat I={Package} label="Unidades" value={stats.units}/></div><Chart days={days}/><section className="seller-card"><div className="seller-title"><div><span>Rendimiento</span><h2>Productos más vendidos</h2></div><ArrowUpRight size={17}/></div>{topProducts.length?<div className="seller-ranking">{topProducts.map((p,i)=><div key={p.name+i}><b>{i+1}</b><span>{p.name}<small>{p.units} unidades · {money(p.revenue)}</small></span></div>)}</div>:<EmptySmall text="Aún no hay ventas registradas."/>}</section><Alerts low={low} pending={pending}/></>}
 {tab==='productos'&&<Module title="Productos y categorías" icon={Package}><div className="seller-grid-metrics"><Metric label="Publicados" value={data.products.filter(p=>p.status==='approved').length}/><Metric label="Pendientes" value={pending.length}/><Metric label="Inactivos" value={data.products.filter(p=>p.status==='inactive').length}/><Metric label="Total" value={data.products.length}/></div>{data.products.length?<div className="seller-table">{data.products.slice(0,20).map(p=><div key={p.id}><span><b>{p.name}</b><small>SKU/producto · {p.status}</small></span><strong>{money(p.price)}</strong></div>)}</div>:<EmptySmall text="Todavía no has publicado productos."/>}</Module>}
 {tab==='pedidos'&&<Module title="Pedidos y estado de ventas" icon={ShoppingBag}>{data.orders.length?<div className="seller-table">{data.orders.slice(0,20).map(o=><div key={o.id}><span><b>#{o.order_number}</b><small>{new Date(o.created_at).toLocaleDateString('es-MX')} · {o.status}</small></span><strong>{money(o.total)}</strong></div>)}</div>:<EmptySmall text="Aún no hay pedidos para mostrar."/>}</Module>}
 {tab==='ingresos'&&<Module title="Ingresos y ganancias" icon={DollarSign}><div className="seller-stats"><Stat I={DollarSign} label="Ventas" value={money(stats.revenue)}/><Stat I={TrendingUp} label="Ganancia" value={money(stats.profit)}/></div><div className="seller-finance"><p><span>Ingresos brutos</span><b>{money(stats.revenue)}</b></p><p><span>Costos registrados</span><b>{money(stats.cost)}</b></p><p className="total"><span>Ganancia</span><b>{money(stats.profit)}</b></p></div><p className="seller-note">La ganancia se calcula con el costo de cada producto cuando está registrado. No se inventa un margen fijo.</p></Module>}
 {tab==='inventario'&&<Module title="Inventario y existencias" icon={Boxes}><div className="seller-grid-metrics"><Metric label="Productos" value={data.products.length}/><Metric label="Stock bajo" value={low.length}/><Metric label="Sin existencias" value={data.products.filter(p=>Number(p.stock||0)===0).length}/></div>{low.length?<div className="seller-table">{low.map(p=><div key={p.id}><span><b>{p.name}</b><small>Existencias: {p.stock}</small></span><strong className="danger">{p.stock}</strong></div>)}</div>:<EmptySmall text="No hay productos con stock bajo."/>}</Module>}
 {tab==='clientes'&&<Module title="Clientes" icon={Users}><div className="seller-big-number">{stats.customers}<small>clientes con pedidos</small></div><p className="seller-note">El panel muestra únicamente el conteo necesario para operar tu tienda; no expone información privada innecesaria.</p></Module>}
 {tab==='configuracion'&&<Module title="Configuración de la tienda" icon={Settings}><div className="seller-settings"><div><span>Nombre</span><b>{data.store.store_name}</b></div><div><span>Estado</span><b>{data.store.status}</b></div><div><span>Descripción</span><b>{data.store.description||'Sin descripción'}</b></div></div></Module>}
 </main>}
function Stat({I,label,value,hint}){return <article className="seller-stat"><I/><small>{label}</small><strong>{value}</strong>{hint&&<em>{hint}</em>}</article>}
function Metric({label,value}){return <div className="seller-metric"><span>{label}</span><b>{value}</b></div>}
function Chart({days}){const max=Math.max(1,...days.map(x=>x.value));return <section className="seller-card"><div className="seller-title"><div><span>Ventas</span><h2>Últimos 7 días</h2></div><BarChart3 size={18}/></div><div className="seller-chart">{days.map(d=><div className="seller-bar-wrap" key={d.label}><div className="seller-bar" style={{height:`${Math.max(5,d.value/max*100)}%`}} title={money(d.value)}/><small>{d.label}</small></div>)}</div></section>}
function Alerts({low,pending}){if(!low.length&&!pending.length)return <section className="seller-card seller-ok"><CheckCircle2 size={18}/><div><b>Todo en orden</b><p>No tienes alertas de inventario ni productos pendientes.</p></div></section>;return <section className="seller-card seller-warning"><AlertCircle size={18}/><div><b>Alertas y pendientes</b><p>{low.length?`${low.length} producto(s) con stock bajo. `:''}{pending.length?`${pending.length} producto(s) pendientes de aprobación.`:''}</p></div></section>}
function Module({title,icon:I,children}){return <section className="seller-module"><div className="seller-module-title"><I size={19}/><div><span>Gestión</span><h2>{title}</h2></div></div>{children}</section>}
function EmptySmall({text}){return <div className="seller-empty-small"><Clock size={20}/><p>{text}</p></div>}
