import React,{useEffect,useMemo,useState}from'react';
import{ChevronLeft,RefreshCw,Store,Package,ShoppingBag,DollarSign,TrendingUp,Users,AlertCircle,BarChart3,Boxes,Settings,Clock,CheckCircle2,Plus,Edit3,Trash2,Save,X,History,Truck}from'lucide-react';
import'./seller-dashboard.css';
import{getMySellerStore,saveMySellerStore,createSellerProduct,updateSellerProduct,deleteSellerProduct,restockSellerProduct,loadSellerInventoryMovements}from'./commercialApi.js';
const URL='https://oycwqpqoxgohzqivclzd.supabase.co',KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_OIoqR1IOg5t3BIQR7g6_0w_1KWzgpY';
const session=()=>{try{return JSON.parse(localStorage.getItem('vanidaxi-auth-session')||'null')}catch{return null}};
const money=n=>`$${Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function rest(path){const s=session(),r=await fetch(`${URL}/rest/v1/${path}`,{headers:{apikey:KEY,Authorization:`Bearer ${s?.access_token||KEY}`}});if(!r.ok)throw Error(await r.text());return r.json()}
const blank={id:null,category_id:'',name:'',description:'',price:'',compare_at_price:'',cost_price:'',stock:'0',sku:'',image_url:'',images:[]};
export default function SellerDashboard({go}){
 const[data,setData]=useState({store:null,products:[],items:[],orders:[],categories:[],customers:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('resumen'),[form,setForm]=useState(null),[saving,setSaving]=useState(false),[toast,setToast]=useState(''),[movements,setMovements]=useState([]);
 const load=async()=>{setLoading(true);setError('');try{const owner=session()?.user?.id;if(!owner)throw Error('Inicia sesión para acceder al panel de vendedor.');const profiles=await rest(`profiles?select=id,full_name,role,is_active&id=eq.${encodeURIComponent(owner)}&limit=1`);if(profiles?.[0]?.role!=='seller')throw Error('Esta sección está disponible para cuentas de vendedor.');const store=await getMySellerStore();if(!store){setData({store:null,products:[],items:[],orders:[],categories:[],customers:[]});return}const sid=encodeURIComponent(store.id);const[products,categories,items]=await Promise.all([rest(`products?select=id,seller_id,category_id,name,slug,description,price,compare_at_price,cost_price,stock,sku,image_url,images,status,rejection_reason,created_at,updated_at&seller_id=eq.${sid}&order=created_at.desc`).catch(()=>[]),rest('categories?select=id,name,slug&is_active=eq.true&order=name').catch(()=>[]),rest(`order_items?select=id,order_id,product_id,product_name,quantity,unit_price,total_price,created_at&seller_id=eq.${sid}&order=created_at.desc`).catch(()=>[])]);const ids=[...new Set(items.map(x=>x.order_id).filter(Boolean))];const orders=ids.length?await rest(`orders?select=id,order_number,user_id,status,total,created_at&id=in.(${ids.map(encodeURIComponent).join(',')})&order=created_at.desc`).catch(()=>[]):[];setData({store,products,categories,items,orders,customers:[...new Set(orders.map(x=>x.user_id).filter(Boolean))]})}catch(e){setError(e?.message||'No fue posible cargar el panel.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const om=new Map(data.orders.map(o=>[o.id,o]));const valid=new Set(['paid','processing','shipped','delivered']);const items=data.items.filter(x=>valid.has(om.get(x.order_id)?.status));const revenue=items.reduce((a,x)=>a+Number(x.total_price||0),0),cost=items.reduce((a,x)=>a+Number(data.products.find(p=>p.id===x.product_id)?.cost_price||0)*Number(x.quantity||0),0);return{revenue,cost,profit:revenue-cost,units:items.reduce((a,x)=>a+Number(x.quantity||0),0),orders:new Set(items.map(x=>x.order_id)).size,customers:new Set(data.orders.filter(o=>valid.has(o.status)).map(o=>o.user_id).filter(Boolean)).size}},[data]);
 const low=data.products.filter(p=>Number(p.stock||0)<=5&&p.status!=='inactive'),pending=data.products.filter(p=>p.status==='pending');
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(Date.now()-(6-i)*86400000),key=d.toISOString().slice(0,10),v=data.items.filter(x=>x.created_at?.slice(0,10)===key).reduce((a,x)=>a+Number(x.total_price||0),0);return{label:d.toLocaleDateString('es-MX',{weekday:'short'}).replace('.',''),value:v}}),[data.items]);
 const top=useMemo(()=>{const m=new Map();data.items.forEach(x=>{const a=m.get(x.product_id)||{name:x.product_name,units:0,revenue:0};a.units+=Number(x.quantity||0);a.revenue+=Number(x.total_price||0);m.set(x.product_id,a)});return[...m.values()].sort((a,b)=>b.units-a.units).slice(0,5)},[data.items]);
 const saveProduct=async()=>{if(!form?.name.trim()||form.price==='')return setToast('Nombre y precio son obligatorios.');setSaving(true);try{if(form.id)await updateSellerProduct(form);else await createSellerProduct(form);setToast(form.id?'Producto actualizado. Quedará pendiente de revisión si ya estaba publicado.':'Producto creado y enviado a aprobación.');setForm(null);await load()}catch(e){setToast(e?.message||'No se pudo guardar el producto.')}finally{setSaving(false)}};
 const remove=async p=>{if(!window.confirm(`¿Eliminar “${p.name}”?`))return;try{await deleteSellerProduct(p.id);setToast('Producto eliminado.');await load()}catch(e){setToast(e?.message||'No se pudo eliminar.')}};
 const restock=async p=>{const q=window.prompt(`Cantidad a agregar a “${p.name}”:`,`10`);if(q===null)return;const n=Number(q);if(!Number.isInteger(n)||n<=0)return setToast('La cantidad debe ser un entero positivo.');try{await restockSellerProduct(p.id,n,'Reposición desde panel de vendedor');setToast('Inventario actualizado.');await load()}catch(e){setToast(e?.message||'No se pudo actualizar el inventario.')}};
 const showHistory=async p=>{try{setMovements(await loadSellerInventoryMovements(p.id));setTab('inventario')}catch(e){setToast(e?.message||'No se pudo cargar el historial.')}};
 if(loading)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><RefreshCw className="spin"/><h2>Cargando panel…</h2><p>Consultando tienda, productos, inventario y ventas reales.</p></div></main>;
 if(error)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><AlertCircle/><h2>No disponible</h2><p>{error}</p><button onClick={()=>go('profile')}>Volver a mi cuenta</button></div></main>;
 if(!data.store)return <main className="scroll-page seller-dashboard"><div className="seller-loading"><Store/><h2>Configura tu tienda</h2><p>Aún no existe una tienda para esta cuenta de vendedor.</p><button onClick={()=>setForm({store_name:'',description:'',logo_url:'',banner_url:''})}><Plus size={14}/> Crear tienda</button></div></main>;
 const nav=[['resumen','Resumen',BarChart3],['productos','Productos',Package],['pedidos','Pedidos',ShoppingBag],['ingresos','Ingresos',DollarSign],['inventario','Inventario',Boxes],['clientes','Clientes',Users],['configuracion','Tienda',Settings]];
 return <main className="scroll-page seller-dashboard"><header className="seller-top"><button className="icon-btn" onClick={()=>go('profile')}><ChevronLeft size={18}/></button><div><span>VaniDaxi · Vendedor</span><h1>{data.store.store_name}</h1></div><button className="icon-btn" onClick={load}><RefreshCw size={16}/></button></header>
 <section className="seller-welcome"><div><small>Panel de control</small><h2>Gestiona tu negocio</h2><p>Productos, inventario, pedidos y rendimiento conectados a Supabase.</p></div><span className="store-status"><CheckCircle2 size={13}/> {data.store.status==='approved'?'Activa':data.store.status}</span></section>
 <nav className="seller-tabs">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={14}/>{label}</button>)}</nav>{toast&&<div className="seller-toast">{toast}<button onClick={()=>setToast('')}><X size={13}/></button></div>}
 {tab==='resumen'&&<><div className="seller-stats"><Stat I={DollarSign} label="Ingresos" value={money(stats.revenue)}/><Stat I={TrendingUp} label="Ganancia" value={money(stats.profit)}/><Stat I={ShoppingBag} label="Pedidos" value={stats.orders}/><Stat I={Package} label="Unidades" value={stats.units}/></div><Chart days={days}/><section className="seller-card"><div className="seller-title"><div><span>Rendimiento</span><h2>Más vendidos</h2></div></div>{top.length?<div className="seller-ranking">{top.map((p,i)=><div key={p.name+i}><b>{i+1}</b><span>{p.name}<small>{p.units} unidades · {money(p.revenue)}</small></span></div>)}</div>:<EmptySmall text="Aún no hay ventas registradas."/>}</section><Alerts low={low} pending={pending}/></>}
 {tab==='productos'&&<Module title="Productos y categorías"><div className="seller-actions"><button onClick={()=>setForm({...blank})}><Plus size={14}/> Nuevo producto</button></div><div className="seller-grid-metrics"><Metric label="Publicados" value={data.products.filter(p=>p.status==='approved').length}/><Metric label="Pendientes" value={pending.length}/><Metric label="Rechazados" value={data.products.filter(p=>p.status==='rejected').length}/><Metric label="Total" value={data.products.length}/></div>{data.products.length?<div className="seller-table">{data.products.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.status} · stock {p.stock}{p.rejection_reason?` · ${p.rejection_reason}`:''}</small></span><strong>{money(p.price)}</strong><aside><button title="Editar" onClick={()=>setForm({...p,compare_at_price:p.compare_at_price??'',cost_price:p.cost_price??''})}><Edit3 size={13}/></button><button title="Eliminar" onClick={()=>remove(p)}><Trash2 size={13}/></button></aside></div>)}</div>:<EmptySmall text="Todavía no has publicado productos."/>}</Module>}
 {tab==='pedidos'&&<Module title="Pedidos y estado de ventas"><p className="seller-note"><Truck size={13}/> Los pedidos locales siguen el flujo Vendedor → VaniDaxi → Comprador. El vendedor no marca la entrega final por su cuenta.</p>{data.orders.length?<div className="seller-table">{data.orders.slice(0,30).map(o=><div key={o.id}><span><b>#{o.order_number}</b><small>{new Date(o.created_at).toLocaleDateString('es-MX')} · {o.status}</small></span><strong>{money(o.total)}</strong></div>)}</div>:<EmptySmall text="Aún no hay pedidos para mostrar."/>}</Module>}
 {tab==='ingresos'&&<Module title="Ingresos y ganancias"><div className="seller-stats"><Stat I={DollarSign} label="Ventas" value={money(stats.revenue)}/><Stat I={TrendingUp} label="Ganancia" value={money(stats.profit)}/></div><div className="seller-finance"><p><span>Ingresos brutos</span><b>{money(stats.revenue)}</b></p><p><span>Costos registrados</span><b>{money(stats.cost)}</b></p><p className="total"><span>Ganancia</span><b>{money(stats.profit)}</b></p></div><p className="seller-note">La ganancia usa el costo registrado de cada producto; no se inventa un margen.</p></Module>}
 {tab==='inventario'&&<Module title="Inventario y existencias"><div className="seller-grid-metrics"><Metric label="Productos" value={data.products.length}/><Metric label="Stock bajo" value={low.length}/><Metric label="Sin existencias" value={data.products.filter(p=>Number(p.stock||0)===0).length}/></div>{data.products.length?<div className="seller-table">{data.products.map(p=><div key={p.id}><span><b>{p.name}</b><small>Existencias: {p.stock} · {p.status}</small></span><strong className={Number(p.stock)<=5?'danger':''}>{p.stock}</strong><aside><button onClick={()=>restock(p)}><Plus size={13}/></button><button onClick={()=>showHistory(p)}><History size={13}/></button></aside></div>)}</div>:<EmptySmall text="No hay productos en inventario."/>}{movements.length>0&&<div className="seller-history"><h3>Historial de movimientos</h3>{movements.slice(0,30).map(m=><div key={m.id}><span>{m.movement_type}<small>{new Date(m.created_at).toLocaleString('es-MX')}</small></span><b>{m.quantity_delta>0?'+':''}{m.quantity_delta}</b><em>{m.stock_before} → {m.stock_after}</em></div>)}</div>}</Module>}
 {tab==='clientes'&&<Module title="Clientes"><div className="seller-big-number">{stats.customers}<small>clientes con pedidos</small></div><p className="seller-note">Se muestra solo el conteo necesario para operar la tienda.</p></Module>}
 {tab==='configuracion'&&<Module title="Configuración de la tienda"><button className="seller-primary" onClick={()=>setForm({store_name:data.store.store_name,description:data.store.description||'',logo_url:data.store.logo_url||'',banner_url:data.store.banner_url||''})}><Edit3 size={14}/> Editar tienda</button><div className="seller-settings"><div><span>Nombre</span><b>{data.store.store_name}</b></div><div><span>Estado</span><b>{data.store.status}</b></div><div><span>Descripción</span><b>{data.store.description||'Sin descripción'}</b></div></div></Module>}
 {form&&('store_name' in form?<StoreForm form={form} setForm={setForm} saving={saving} onSave={async()=>{setSaving(true);try{const s=await saveMySellerStore(form);setForm(null);setToast('Tienda guardada. Estado: '+(s?.status||'pending'));await load()}catch(e){setToast(e?.message||'No se pudo guardar la tienda.')}finally{setSaving(false)}}}/>:<ProductForm form={form} setForm={setForm} categories={data.categories} saving={saving} onSave={saveProduct}/>)}</main>}
function Stat({I,label,value}){return <article className="seller-stat"><I/><small>{label}</small><strong>{value}</strong></article>}
function Metric({label,value}){return <div className="seller-metric"><span>{label}</span><b>{value}</b></div>}
function Chart({days}){const max=Math.max(1,...days.map(x=>x.value));return <section className="seller-card"><div className="seller-title"><div><span>Ventas</span><h2>Últimos 7 días</h2></div><BarChart3 size={18}/></div><div className="seller-chart">{days.map(d=><div className="seller-bar-wrap" key={d.label}><div className="seller-bar" style={{height:`${Math.max(5,d.value/max*100)}%`}} title={money(d.value)}/><small>{d.label}</small></div>)}</div></section>}
function Alerts({low,pending}){if(!low.length&&!pending.length)return <section className="seller-card seller-ok"><CheckCircle2 size={18}/><div><b>Todo en orden</b><p>No hay alertas de inventario ni productos pendientes.</p></div></section>;return <section className="seller-card seller-warning"><AlertCircle size={18}/><div><b>Alertas</b><p>{low.length?`${low.length} producto(s) con stock bajo. `:''}{pending.length?`${pending.length} producto(s) pendientes de aprobación.`:''}</p></div></section>}
function Module({title,children}){return <section className="seller-module"><div className="seller-module-title"><Package size={19}/><div><span>Gestión</span><h2>{title}</h2></div></div>{children}</section>}
function EmptySmall({text}){return <div className="seller-empty-small"><Clock size={20}/><p>{text}</p></div>}
function Field({label,...p}){return <label className="seller-field"><span>{label}</span><input {...p}/></label>}
function StoreForm({form,setForm,saving,onSave}){return <div className="seller-modal-back"><div className="seller-modal"><button className="seller-close" onClick={()=>setForm(null)}><X/></button><h2>Tu tienda</h2><Field label="Nombre de la tienda" value={form.store_name} onChange={e=>setForm({...form,store_name:e.target.value})} maxLength={120}/><Field label="Descripción" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={2000}/><Field label="Logo URL (opcional)" value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})}/><Field label="Banner URL (opcional)" value={form.banner_url} onChange={e=>setForm({...form,banner_url:e.target.value})}/><button className="seller-primary" disabled={saving} onClick={onSave}><Save size={14}/>{saving?'Guardando…':'Guardar tienda'}</button></div></div>}
function ProductForm({form,setForm,categories,saving,onSave}){const f=(k,v)=>setForm({...form,[k]:v});return <div className="seller-modal-back"><div className="seller-modal"><button className="seller-close" onClick={()=>setForm(null)}><X/></button><h2>{form.id?'Editar producto':'Nuevo producto'}</h2><Field label="Nombre" value={form.name} onChange={e=>f('name',e.target.value)} maxLength={180}/><label className="seller-field"><span>Categoría</span><select value={form.category_id||''} onChange={e=>f('category_id',e.target.value)}><option value="">Sin categoría</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Descripción" value={form.description||''} onChange={e=>f('description',e.target.value)} maxLength={5000}/><div className="seller-form-grid"><Field label="Precio" type="number" min="0" step="0.01" value={form.price} onChange={e=>f('price',e.target.value)}/><Field label="Precio anterior" type="number" min="0" step="0.01" value={form.compare_at_price} onChange={e=>f('compare_at_price',e.target.value)}/><Field label="Costo" type="number" min="0" step="0.01" value={form.cost_price} onChange={e=>f('cost_price',e.target.value)}/><Field label="Stock" type="number" min="0" step="1" value={form.stock} onChange={e=>f('stock',e.target.value)}/></div><Field label="SKU" value={form.sku||''} onChange={e=>f('sku',e.target.value)} maxLength={100}/><Field label="Imagen principal URL (opcional)" value={form.image_url||''} onChange={e=>f('image_url',e.target.value)}/><button className="seller-primary" disabled={saving} onClick={onSave}><Save size={14}/>{saving?'Guardando…':'Guardar producto'}</button></div></div>}
