import React,{useRef,useState}from'react'
import{LogIn,UserPlus,ShieldCheck,Truck,Store,Heart,ArrowRight,Fingerprint,LockKeyhole}from'lucide-react'
import HCaptcha from'@hcaptcha/react-hcaptcha'
import AuthChoice from'./AuthChoice.jsx'
import{supabase}from'./supabaseClient.js'
import{saveSession}from'./auth.js'
import'./welcome-gate.css'

const HCAPTCHA_SITEKEY=import.meta.env.VITE_HCAPTCHA_SITEKEY||'390a44ec-b452-47d4-8514-5e6aeeece0ee'
const passkeySupported=()=>typeof window!=='undefined'&&window.isSecureContext&&'PublicKeyCredential'in window

export default function WelcomeGate({locked=false,onUnlock}){
 const[authOpen,setAuthOpen]=useState(false),[authType,setAuthType]=useState('login'),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[captchaReady,setCaptchaReady]=useState(false);const captchaRef=useRef(null)
 const open=type=>{setAuthType(type);setErr('');setAuthOpen(true)}
 const unlock=async()=>{setErr('');if(!passkeySupported()){setErr('Este dispositivo o navegador no tiene disponible la llave de acceso. Usa tu contraseña para continuar.');return}if(!captchaReady||!captchaRef.current){setErr('La verificación de seguridad todavía se está preparando. Espera un momento e inténtalo de nuevo.');return}setBusy(true);try{const captcha=await captchaRef.current.execute({async:true});const captchaToken=captcha?.response||captcha?.token||captchaRef.current.getResponse?.();if(!captchaToken)throw new Error('No se pudo completar la verificación de seguridad. Inténtalo de nuevo.');const{data,error}=await supabase.auth.signInWithPasskey({options:{captchaToken}});captchaRef.current.resetCaptcha?.();if(error)throw error;if(!data?.session)throw new Error('No se recibió una sesión válida.');saveSession(data.session);localStorage.removeItem('vanidaxi-app-lock');onUnlock?.()}catch(e){captchaRef.current?.resetCaptcha?.();if(e?.name==='NotAllowedError')setErr('La verificación del dispositivo fue cancelada.');else if(e?.code==='passkey_disabled')setErr('La llave de acceso no está disponible en este momento.');else setErr(e?.message||'No se pudo desbloquear la cuenta. Puedes usar tu contraseña.')}finally{setBusy(false)}}
 if(locked)return <div className="vd-welcome vd-welcome-locked"><div className="vd-welcome-scene" aria-hidden="true"></div><div className="vd-welcome-shade" aria-hidden="true"></div><header className="vd-welcome-brand"><div className="vd-welcome-logo"><span>V</span></div><b>Vani<span>Daxi</span></b><small>COMPRA · VENDE · DISFRUTA</small></header><main className="vd-welcome-content vd-welcome-lock-content"><div className="vd-welcome-lock-icon"><LockKeyhole size={30}/></div><div className="vd-welcome-copy"><em>Tu cuenta está protegida</em><h1>Bienvenido de nuevo a <strong>VaniDaxi</strong></h1><p>Verifica tu dispositivo para continuar de forma segura.</p></div><div className="vd-welcome-actions"><button className="vd-welcome-primary" onClick={unlock} disabled={busy||!captchaReady}><Fingerprint/><span>{busy?'Verificando…':!captchaReady?'Preparando verificación…':'Desbloquear con huella, Face ID o PIN'}</span><ArrowRight/></button><button className="vd-welcome-secondary" onClick={()=>open('login')} disabled={busy}><LogIn/><span>Continuar con contraseña</span><ArrowRight/></button></div><div className="vd-hidden-captcha"><HCaptcha ref={captchaRef} sitekey={HCAPTCHA_SITEKEY} size="invisible" onReady={()=>setCaptchaReady(true)} onLoad={()=>setCaptchaReady(true)} onError={()=>{setCaptchaReady(false);setErr('No se pudo completar la verificación de seguridad. Inténtalo de nuevo.')}} onExpire={()=>setCaptchaReady(true)}/></div>{err&&<div className="vd-welcome-error">{err}</div>}</main><footer className="vd-welcome-footer"><ShieldCheck size={15}/> Acceso seguro a tu cuenta</footer>{authOpen&&<AuthChoice type={authType} close={()=>setAuthOpen(false)} done={()=>{setAuthOpen(false);localStorage.removeItem('vanidaxi-app-lock');onUnlock?.()}}/>}</div>
 return <div className="vd-welcome"><div className="vd-welcome-scene" aria-hidden="true"></div><div className="vd-welcome-shade" aria-hidden="true"></div><header className="vd-welcome-brand"><div className="vd-welcome-logo"><span>V</span></div><b>Vani<span>Daxi</span></b><small>COMPRA · VENDE · DISFRUTA</small></header><main className="vd-welcome-content"><div className="vd-welcome-copy"><em>Hola,</em><h1>Bienvenido a <strong>VaniDaxi</strong></h1><p>Todo lo que necesitas para <b>comprar, vender y recibir</b> en un solo lugar.</p></div><div className="vd-welcome-actions"><button className="vd-welcome-primary" onClick={()=>open('login')}><LogIn/><span>Iniciar sesión</span><ArrowRight/></button><button className="vd-welcome-secondary" onClick={()=>open('signup')}><UserPlus/><span>Crear cuenta</span><ArrowRight/></button></div><div className="vd-welcome-benefits"><div><ShieldCheck/><span>Compras<br/>seguras</span></div><i></i><div><Truck/><span>Envíos a<br/>todo México</span></div><i></i><div><Store/><span>Vende y haz crecer<br/>tu negocio</span></div><i></i><div><Heart/><span>Todo lo que<br/>te gusta</span></div></div><div className="vd-welcome-dots" aria-hidden="true"><b></b><i></i><i></i></div></main><footer className="vd-welcome-footer"><ShieldCheck size={15}/> Acceso seguro a tu cuenta</footer>{authOpen&&<AuthChoice type={authType} close={()=>setAuthOpen(false)} done={()=>{setAuthOpen(false);location.reload()}}/>}</div>
}
