import React,{useEffect,useRef,useState}from'react'
import{LogIn,UserPlus,ShieldCheck,Fingerprint,ArrowRight,LockKeyhole,ShoppingBag,Store,Sparkles}from'lucide-react'
import HCaptcha from'@hcaptcha/react-hcaptcha'
import AuthChoice from'./AuthChoice.jsx'
import{supabase}from'./supabaseClient.js'
import{saveSession}from'./auth.js'
import'./welcome-gate.css'
import'./welcome-responsive-fix.css'

const HCAPTCHA_SITEKEY=import.meta.env.VITE_HCAPTCHA_SITEKEY||'390a44ec-b452-47d4-8514-5e6aeeece0ee'
const passkeySupported=()=>typeof window!=='undefined'&&window.isSecureContext&&'PublicKeyCredential'in window
const reducedMotion=()=>typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches

export default function WelcomeGate({locked=false,onUnlock}){
 const[authOpen,setAuthOpen]=useState(false),[authType,setAuthType]=useState('login'),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[captchaReady,setCaptchaReady]=useState(false)
 const[panel,setPanel]=useState(0)
 const carouselRef=useRef(null),captchaRef=useRef(null),autoTimerRef=useRef(null)
 const open=type=>{setAuthType(type);setErr('');setAuthOpen(true)}
 const goPanel=index=>{setPanel(index);carouselRef.current?.children?.[index]?.scrollIntoView({behavior:reducedMotion()?'auto':'smooth',block:'nearest',inline:'center'})}
 const stopAutoSlide=()=>{if(autoTimerRef.current){clearInterval(autoTimerRef.current);autoTimerRef.current=null}}
 const resetAutoSlide=()=>{stopAutoSlide();if(locked||authOpen||reducedMotion()||document.visibilityState==='hidden')return;autoTimerRef.current=setInterval(()=>{const next=panel===0?1:0;goPanel(next)},5000)}
 useEffect(()=>{resetAutoSlide();const onVisibility=()=>document.visibilityState==='hidden'?stopAutoSlide():resetAutoSlide();document.addEventListener('visibilitychange',onVisibility);return()=>{stopAutoSlide();document.removeEventListener('visibilitychange',onVisibility)}},[panel,locked,authOpen])
 useEffect(()=>{const onMotion=()=>resetAutoSlide();const m=window.matchMedia?.('(prefers-reduced-motion: reduce)');m?.addEventListener?.('change',onMotion);return()=>m?.removeEventListener?.('change',onMotion)},[panel,locked,authOpen])
 const unlock=async()=>{setErr('');if(!passkeySupported()){setErr('Este dispositivo o navegador no tiene disponible la llave de acceso. Usa tu contraseña para continuar.');return}if(!captchaReady||!captchaRef.current){setErr('La verificación de seguridad todavía se está preparando. Espera un momento e inténtalo de nuevo.');return}setBusy(true);try{const captcha=await captchaRef.current.execute({async:true});const captchaToken=captcha?.response||captcha?.token||captchaRef.current.getResponse?.();if(!captchaToken)throw new Error('No se pudo completar la verificación de seguridad. Inténtalo de nuevo.');const{data,error}=await supabase.auth.signInWithPasskey({options:{captchaToken}});captchaRef.current.resetCaptcha?.();if(error)throw error;if(!data?.session)throw new Error('No se recibió una sesión válida.');saveSession(data.session);localStorage.removeItem('vanidaxi-app-lock');onUnlock?.()}catch(e){captchaRef.current?.resetCaptcha?.();if(e?.name==='NotAllowedError')setErr('La verificación del dispositivo fue cancelada.');else if(e?.code==='passkey_disabled')setErr('La llave de acceso no está disponible en este momento.');else setErr(e?.message||'No se pudo desbloquear la cuenta. Puedes usar tu contraseña.')}finally{setBusy(false)}}
 if(locked)return <div className="vd-welcome vd-welcome-locked"><div className="vd-welcome-scene" aria-hidden="true"></div><div className="vd-welcome-shade" aria-hidden="true"></div><header className="vd-welcome-brand"><div className="vd-welcome-logo"><span>V</span></div><b>Vani<span>Daxi</span></b><small>COMPRA · VENDE · DISFRUTA</small></header><main className="vd-welcome-content vd-welcome-lock-content"><div className="vd-welcome-lock-icon"><LockKeyhole size={30}/></div><div className="vd-welcome-copy"><em>Tu cuenta está protegida</em><h1>Bienvenido de nuevo a <strong>VaniDaxi</strong></h1><p>Verifica tu dispositivo para continuar de forma segura.</p></div><div className="vd-welcome-actions"><button className="vd-welcome-primary" onClick={unlock} disabled={busy||!captchaReady}><Fingerprint/><span>{busy?'Verificando…':!captchaReady?'Preparando verificación…':'Desbloquear con huella, Face ID o PIN'}</span><ArrowRight/></button><button className="vd-welcome-secondary" onClick={()=>open('login')} disabled={busy}><LogIn/><span>Continuar con contraseña</span><ArrowRight/></button></div><div className="vd-hidden-captcha"><HCaptcha ref={captchaRef} sitekey={HCAPTCHA_SITEKEY} size="invisible" onReady={()=>setCaptchaReady(true)} onLoad={()=>setCaptchaReady(true)} onError={()=>{setCaptchaReady(false);setErr('No se pudo completar la verificación de seguridad. Inténtalo de nuevo.')}} onExpire={()=>setCaptchaReady(true)}/></div>{err&&<div className="vd-welcome-error">{err}</div>}</main><footer className="vd-welcome-footer"><ShieldCheck size={15}/> Acceso seguro a tu cuenta</footer>{authOpen&&<AuthChoice type={authType} close={()=>setAuthOpen(false)} done={()=>{setAuthOpen(false);localStorage.removeItem('vanidaxi-app-lock');onUnlock?.()}}/>}</div>
 return <div className="vd-welcome vd-welcome-approved"><div ref={carouselRef} className="vd-welcome-carousel" onScroll={e=>{const width=e.currentTarget.clientWidth||1;const next=Math.round(e.currentTarget.scrollLeft/width);if(next!==panel)setPanel(next)}} onTouchStart={stopAutoSlide} onTouchEnd={resetAutoSlide} onMouseEnter={stopAutoSlide} onMouseLeave={resetAutoSlide}>
  <section className="vd-welcome-panel vd-welcome-panel-buyer" aria-label="Comprar en VaniDaxi"><div className="vd-welcome-art" aria-hidden="true"><div className="vd-welcome-glow"></div><div className="vd-welcome-bag"><span>V</span><i></i></div><div className="vd-welcome-float vd-welcome-float-one">✦</div><div className="vd-welcome-float vd-welcome-float-two">♡</div></div><div className="vd-welcome-panel-content"><div className="vd-welcome-kicker"><ShoppingBag size={17}/> TU TIENDA ONLINE</div><h1>Compra lo que<br/><strong>te encanta.</strong></h1><p>Descubre moda, tecnología, hogar y mucho más en VaniDaxi.</p><div className="vd-welcome-panel-actions"><button onClick={()=>open('login')}><LogIn/><span>Iniciar sesión</span></button><button onClick={()=>open('signup')}><UserPlus/><span>Crear cuenta</span></button></div></div><div className="vd-welcome-swipe"><span>Desliza para vender</span><ArrowRight size={17}/></div></section>
  <section className="vd-welcome-panel vd-welcome-panel-seller" aria-label="Vender en VaniDaxi"><div className="vd-welcome-art" aria-hidden="true"><div className="vd-welcome-glow"></div><div className="vd-welcome-store"><Store size={72}/><span>VaniDaxi</span></div><div className="vd-welcome-float vd-welcome-float-one">✦</div><div className="vd-welcome-float vd-welcome-float-two">$</div></div><div className="vd-welcome-panel-content"><div className="vd-welcome-kicker"><Store size={17}/> TU TIENDA EN VaniDaxi</div><h1>Vende y haz<br/><strong>crecer tu tienda.</strong></h1><p>Publica tus productos, recibe pedidos y administra tu negocio desde un solo lugar.</p><div className="vd-welcome-panel-actions"><button onClick={()=>open('login')}><LogIn/><span>Iniciar sesión</span></button><button onClick={()=>open('seller-signup')}><UserPlus/><span>Vender en VaniDaxi</span></button></div></div><div className="vd-welcome-swipe"><ArrowRight size={17}/><span>Desliza para comprar</span></div></section>
 </div><div className="vd-welcome-dots" aria-label="Seleccionar panel"><button className={panel===0?'active':''} aria-label="Panel Comprar" aria-current={panel===0?'page':undefined} onClick={()=>goPanel(0)}></button><button className={panel===1?'active':''} aria-label="Panel Vender" aria-current={panel===1?'page':undefined} onClick={()=>goPanel(1)}></button></div>{authOpen&&<AuthChoice type={authType} close={()=>setAuthOpen(false)} done={()=>{setAuthOpen(false);location.reload()}}/>}</div>
}
