import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"https://jaquelinhm9-dotcom.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const stripeSecret=Deno.env.get("STRIPE_SECRET_KEY");
const supabase=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
async function stripe(path:string,options:RequestInit={}){const response=await fetch(`https://api.stripe.com/v1/${path}`,{...options,headers:{Authorization:`Bearer ${stripeSecret}`,"Content-Type":"application/x-www-form-urlencoded",...(options.headers||{})}});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message||"Stripe request failed");return data}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);if(!stripeSecret)return json({error:"Stripe is not configured"},503);
const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"Authentication required"},401);
const userClient=createClient(supabaseUrl,Deno.env.get("SUPABASE_ANON_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:userError}=await userClient.auth.getUser(token);if(userError||!user)return json({error:"Invalid authentication"},401);
const {data:profile,error:profileError}=await supabase.from("profiles").select("role,is_active").eq("id",user.id).maybeSingle();if(profileError)return json({error:profileError.message},500);if(profile?.role!=="admin"||!profile?.is_active)return json({error:"Administrative authorization required"},403);
const body=await req.json().catch(()=>null) as {return_id?:string;amount?:number;notes?:string}|null;const returnId=body?.return_id;if(!returnId||!/^[0-9a-f-]{36}$/i.test(returnId))return json({error:"Invalid return_id"},400);
const {data:ret,error:returnError}=await supabase.from("returns").select("id,order_id,order_item_id,status,refund_amount,resolution_notes").eq("id",returnId).maybeSingle();if(returnError)return json({error:returnError.message},500);if(!ret)return json({error:"Return not found"},404);
if(ret.status==='refunded')return json({ok:true,already_refunded:true,amount:Number(ret.refund_amount||0),return:ret});if(ret.status!=="received")return json({error:"Return must be received before refund"},409);
const requestedAmount=body?.amount==null?Number(ret.refund_amount||0):Number(body.amount);const maximumAmount=Number(ret.refund_amount||0);if(!Number.isFinite(requestedAmount)||requestedAmount<=0||requestedAmount>maximumAmount)return json({error:"Invalid refund amount"},422);const amountCents=Math.round(requestedAmount*100);if(amountCents<1)return json({error:"Refund amount is too small"},422);
const {data:order,error:orderError}=await supabase.from("orders").select("id,payment_provider,payment_id").eq("id",ret.order_id).maybeSingle();if(orderError)return json({error:orderError.message},500);if(!order)return json({error:"Order not found"},404);if(order.payment_provider!=="stripe"||!order.payment_id)return json({error:"This order does not have a Stripe payment to refund"},409);
try{let paymentIntent=String(order.payment_id);if(!paymentIntent.startsWith("pi_")){if(!paymentIntent.startsWith("cs_"))return json({error:"Stored Stripe payment reference is invalid"},409);const checkoutSession=await stripe(`checkout/sessions/${encodeURIComponent(paymentIntent)}`);paymentIntent=String(checkoutSession?.payment_intent||"");if(!paymentIntent.startsWith("pi_"))return json({error:"Stripe Checkout session has no payment intent"},409)}
const refund=await stripe("refunds",{method:"POST",headers:{"Idempotency-Key":`vani-return-${returnId}`},body:new URLSearchParams({payment_intent:paymentIntent,amount:String(amountCents),reason:"requested_by_customer","metadata[return_id]":returnId,"metadata[order_id]":String(ret.order_id)})});const refundId=String(refund.id||"");
const {data:resolved,error:resolveError}=await supabase.rpc("finalize_return_refund",{p_return_id:returnId,p_notes:body?.notes||`Reembolso Stripe ${refundId}`,p_refund_amount:requestedAmount});if(resolveError)return json({error:"Stripe refund completed but database finalization failed. Retry the same refund safely.",refund_id:refundId,detail:resolveError.message},500);return json({ok:true,refund_id:refundId,amount:requestedAmount,return:resolved});
}catch(error){return json({error:error instanceof Error?error.message:"Stripe refund failed"},502)}});
