import React, { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from './lib/supabaseClient'

function VaniMark({ className = '' }) { return <span className={`vd-mark ${className}`} aria-hidden="true"><span className="vd-mark-v">V</span></span> }

function AuthPanel({ onClose, initialMode = 'register' }) {
  const [mode, setMode] = useState(initialMode), [role, setRole] = useState('buyer'), [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [captchaToken, setCaptchaToken] = useState(''), [captchaRequired, setCaptchaRequired] = useState(false), [loading, setLoading] = useState(false), [message, setMessage] = useState('')
  const captchaRef = useRef(null), widgetId = useRef(null), siteKey = import.meta.env.VITE_HCAPTCHA_SITEKEY || ''
  useEffect(() => { if (!siteKey) return; let cancelled=false; const ensure=()=>{ if(!window.hcaptcha||cancelled)return; if(captchaRef.current&&widgetId.current===null) widgetId.current=window.hcaptcha.render(captchaRef.current,{sitekey:siteKey,callback:t=>setCaptchaToken(t||''),'expired-callback':()=>setCaptchaToken(''),'error-callback':()=>setCaptchaToken('')}) }; if(window.hcaptcha)ensure(); else { let s=document.querySelector('script[data-vanidaxi-hcaptcha]'); if(!s){s=document.createElement('script');s.src='https://js.hcaptcha.com/1/api.js?render=explicit';s.async=true;s.defer=true;s.dataset.vanidaxiHcaptcha='true';document.head.appendChild(s)} s.addEventListener('load',ensure,{once:true}) } return()=>{cancelled=true} },[siteKey])
  const resetCaptcha=useCallback(()=>{setCaptchaToken('');if(window.hcaptcha&&widgetId.current!==null){try{window.hcaptcha.reset(widgetId.current)}catch{}}},[])
  useEffect(()=>{setCaptchaRequired(Boolean(siteKey));resetCaptcha();setMessage('')},[mode,resetCaptcha,siteKey])
  const submit=async e=>{e.preventDefault();setLoading(true);setMessage('');try{if(captchaRequired&&!captchaToken){setMessage('Completa la verificación de seguridad antes de continuar.');return} if(mode==='register'){const cleanEmail=email.trim().toLowerCase(),cleanName=name.trim();if(!cleanName||!cleanEmail||password.length<8){setMessage('Completa tu nombre, un correo válido y una contraseña de al menos 8 caracteres.');return}const{data,error}=await supabase.auth.signUp({email:cleanEmail,password,options:{captchaToken:captchaToken||undefined,data:{display_name:cleanName,onboarding_role:role}}});if(error)throw error;setMessage(data.session?'Cuenta creada. La siguiente etapa configurará tu experiencia según el rol elegido.':'Cuenta creada. Revisa tu correo para confirmar la cuenta y después inicia sesión.');resetCaptcha();return}const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password,options:captchaToken?{captchaToken}:undefined});if(error)throw error;setMessage('Inicio de sesión correcto. Preparando tu experiencia VaniDaxi...')}catch(error){setMessage(error?.message||'No fue posible completar la operación.');resetCaptcha()}finally{setLoading(false)}}
  const oauth=async provider=>{setLoading(true);setMessage('');try{const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin+window.location.pathname}});if(error)throw error}catch(error){setMessage(error?.message||`No fue posible iniciar sesión con ${provider}.`)}finally{setLoading(false)}}
  return <div className="auth-overlay" role="dialog" aria-modal="true"><button className="auth-backdrop" onClick={onClose} aria-label="Cerrar"/><section className="auth-panel"><div className="auth-top"><button className="auth-close" onClick={onClose} aria-label="Cerrar">×</button><VaniMark/><div><span className="eyebrow">VaniDaxi</span><h2>{mode==='register'?'Crea tu cuenta':'Bienvenido de nuevo'}</h2></div></div><div className="auth-tabs"><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Crear cuenta</button><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Iniciar sesión</button></div>{mode==='register'&&<div className="role-choice"><span className="field-label">¿Cómo usarás VaniDaxi?</span><div className="role-grid"><button type="button" className={role==='buyer'?'role-card active':'role-card'} onClick={()=>setRole('buyer')}><span className="role-icon">🛍️</span><strong>Comprar</strong><small>Explora y compra</small></button><button type="button" className={role==='seller'?'role-card active':'role-card'} onClick={()=>setRole('seller')}><span className="role-icon">🏪</span><strong>Vender / Empresa</strong><small>Gestiona tu tienda</small></button></div></div>}<form onSubmit={submit} className="auth-form">{mode==='register'&&<label><span>Nombre</span><input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label><span>Correo electrónico</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label><span>Contraseña</span><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete={mode==='register'?'new-password':'current-password'}/></label>{mode==='register'&&<p className="password-hint">Usa al menos 8 caracteres.</p>}{siteKey&&<div ref={captchaRef} className="captcha-slot"/>}<button className="primary-action" type="submit" disabled={loading||(captchaRequired&&!captchaToken)}>{loading?'Procesando…':mode==='register'?'Crear cuenta':'Iniciar sesión'}</button></form><div className="divider"><span>o continúa con</span></div><div className="social-row"><button type="button" onClick={()=>oauth('google')} disabled={loading}><strong>G</strong><span>Google</span></button><button type="button" onClick={()=>oauth('facebook')} disabled={loading}><strong>f</strong><span>Facebook</span></button></div>{message&&<div className="auth-message" role="status">{message}</div>}<p className="legal-note">Al continuar, aceptas los términos aplicables y reconoces el aviso de privacidad de VaniDaxi.</p></section></div>
}

function Welcome(){const[scene,setScene]=useState('buyer'),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState('register'),start=useRef(null);const openAuth=m=>{setAuthMode(m);setAuthOpen(true)};const down=e=>{start.current=e.clientX};const up=e=>{if(start.current===null)return;const d=e.clientX-start.current;start.current=null;if(Math.abs(d)>=55)setScene(d<0?'seller':'buyer')};return <main className="welcome-shell"><div className="welcome-stage" onPointerDown={down} onPointerUp={up}><div className={`welcome-scene ${scene}`}><img className="welcome-art" src={scene==='buyer'?`${import.meta.env.BASE_URL}welcome-buyer.svg`:`${import.meta.env.BASE_URL}welcome-seller.svg`} alt="" draggable="false"/></div><button className="welcome-hit welcome-hit-swipe" aria-label="Cambiar vista"/><button className="welcome-hit welcome-hit-login" onClick={()=>openAuth('login')} aria-label="Iniciar sesión"/><button className="welcome-hit welcome-hit-register" onClick={()=>openAuth('register')} aria-label="Crear cuenta"/><button className="welcome-hit welcome-hit-skip" onClick={()=>openAuth('login')}>Omitir</button></div>{authOpen&&<AuthPanel initialMode={authMode} onClose={()=>setAuthOpen(false)}/>}</main>}

export default function App(){useEffect(()=>{const{data}=supabase.auth.onAuthStateChange(()=>{});return()=>data.subscription.unsubscribe()},[]);return <Welcome/>}
